[CmdletBinding()]
param([switch]$RepositoryOnly,[switch]$NoClean,[int]$Jobs=24)
$ErrorActionPreference='Stop'
$scriptRoot=Split-Path -Parent $MyInvocation.MyCommand.Path
$repositoryRoot=(Resolve-Path (Join-Path $scriptRoot '..\..\..')).Path
$preflight=Join-Path $scriptRoot 'preflight_checkpoint_159.py'
$contract=Join-Path $scriptRoot 'test_checkpoint_159_contract.py'
$research=Join-Path $repositoryRoot 'tools\simulation\run_starcluster_research.py'
$study=Join-Path $repositoryRoot 'docs\archive\testing\pre-cp165-active\cp159_aux_closure_study_v0_1.json'
$outRoot=Join-Path $repositoryRoot 'out\checkpoint-159'
$testOut=Join-Path $outRoot 'xunit';$parityOut=Join-Path $outRoot 'research-parity';$deterministicOut=Join-Path $outRoot 'deterministic-scenarios';$tl1PhaseAOut=Join-Path $outRoot 'tl1-phase-a'
$planOut=Join-Path $outRoot 'aux-closure-plan';$smokeOut=Join-Path $outRoot 'aux-closure-smoke';$baselineOut=Join-Path $outRoot 'baseline';$fieldScreenRoot=Join-Path $outRoot 'field-screen';$fieldMerged=Join-Path $outRoot 'field-screen-merged';$crystalScreenRoot=Join-Path $outRoot 'crystal-screen';$crystalMerged=Join-Path $outRoot 'crystal-screen-merged';$fieldDeepOut=Join-Path $outRoot 'field-deep';$crystalDeepOut=Join-Path $outRoot 'crystal-deep';$interactionOut=Join-Path $outRoot 'field-hardener-interactions';$droneOut=Join-Path $outRoot 'repair-drone-micro';$snapshotOut=Join-Path $outRoot 'pf3-snapshot'
$repoOnlySummary=Join-Path $outRoot 'CP159_REPOSITORY_ONLY_ACCEPTANCE.json';$finalSummary=Join-Path $outRoot 'CP159_NATIVE_ACCEPTANCE_SUMMARY.json'
function Get-Cpython313Command { foreach($c in @(@{Command='py';Args=@('-3.13')},@{Command='python';Args=@()},@{Command='python3';Args=@()})){if(Get-Command $c.Command -ErrorAction SilentlyContinue){$v=& $c.Command @($c.Args+@('--version')) 2>&1|Out-String;if($LASTEXITCODE -eq 0 -and $v -match 'Python\s+3\.13(?:\.|\s|$)'){return $c}}};throw 'CP159 requires Python 3.13.' }
function Invoke-PythonChecked([object]$Python,[string[]]$Arguments,[string]$Failure){& $Python.Command @($Python.Args+$Arguments);if($LASTEXITCODE -ne 0){throw "$Failure (exit code $LASTEXITCODE)."}}
function Invoke-Captured([string]$Label,[string]$LogPath,[scriptblock]$Body){$old=$ErrorActionPreference;try{$ErrorActionPreference='Continue';& $Body *> $LogPath;$code=$LASTEXITCODE}finally{$ErrorActionPreference=$old};if($code -ne 0){Write-Host "       $Label output tail:" -ForegroundColor Yellow;Get-Content -LiteralPath $LogPath -Tail 120|ForEach-Object{Write-Host("       $_")};throw "$Label failed (exit code $code)."}}
function Read-Json([string]$Path){return(Get-Content -LiteralPath $Path -Raw|ConvertFrom-Json)}
function Invoke-AuxChecked([string[]]$Arguments,[string]$Failure){$sim=Join-Path $repositoryRoot 'tools\simulation';$oldPath=$env:PYTHONPATH;try{if([string]::IsNullOrWhiteSpace($oldPath)){$env:PYTHONPATH=$sim}else{$env:PYTHONPATH=$sim+[IO.Path]::PathSeparator+$oldPath};& $python.Command @($python.Args+@('-B','-m','starcluster_research.auxiliary_closure','--repo',$repositoryRoot,'--study',$study)+$Arguments);if($LASTEXITCODE -ne 0){throw "$Failure (exit code $LASTEXITCODE)."}}finally{$env:PYTHONPATH=$oldPath}}
function Invoke-PythonResearchTests {$files=@(Get-ChildItem -LiteralPath (Join-Path $repositoryRoot 'tools\simulation\tests') -Filter 'test_*.py'|Sort-Object Name);if($files.Count -ne 50){throw "CP159 expected 50 Python modules, found $($files.Count)."};$sim=Join-Path $repositoryRoot 'tools\simulation';$oldPath=$env:PYTHONPATH;try{if([string]::IsNullOrWhiteSpace($oldPath)){$env:PYTHONPATH=$sim}else{$env:PYTHONPATH=$sim+[IO.Path]::PathSeparator+$oldPath};$chunkSize=8;$chunks=[Math]::Ceiling($files.Count/[double]$chunkSize);for($c=0;$c -lt $chunks;$c++){$start=$c*$chunkSize;$end=[Math]::Min($files.Count-1,$start+$chunkSize-1);$mods=@($files[$start..$end]|ForEach-Object{"tools.simulation.tests.$($_.BaseName)"});Write-Host("       Python test chunk {0}/{1} ({2} modules)..." -f ($c+1),$chunks,$mods.Count);& $python.Command @($python.Args+@('-B','-m','unittest')+$mods);if($LASTEXITCODE -ne 0){throw "CP159 Python chunk $($c+1) failed."}}}finally{$env:PYTHONPATH=$oldPath}}
function Valid-Summary([string]$Path,[string]$Mode,[int64]$Trials=-1,[string]$TrialField='combatTrials'){if(-not(Test-Path $Path)){return $false};try{$s=Read-Json $Path;if(-not[bool]$s.passed -or [string]$s.mode -ne $Mode){return $false};if($Trials -ge 0 -and [int64]$s.$TrialField -ne $Trials){return $false};if($s.PSObject.Properties.Name -contains 'errors' -and [int]$s.errors -ne 0){return $false};if($s.PSObject.Properties.Name -contains 'errorTrials' -and [int]$s.errorTrials -ne 0){return $false};return $true}catch{return $false}}
function Copy-Pf3Snapshot {if(Test-Path $snapshotOut){Remove-Item -Recurse -Force $snapshotOut};New-Item -ItemType Directory -Force -Path $snapshotOut|Out-Null;$ev=Join-Path $repositoryRoot 'docs\validation\evidence\checkpoint-159';foreach($n in @('research_execution_baseline_manifest_v0_3.json','pf3_conformance_report_v0_1.json','aux_pending_finalization_promotion_ledger_v0_1.csv')){Copy-Item -LiteralPath (Join-Path $ev $n) -Destination $snapshotOut};Copy-Item -LiteralPath (Join-Path $repositoryRoot 'docs\archive\player_technology\pre-cp165-active\technology_research_execution_baseline_pending_finalization_v0_3.json') -Destination $snapshotOut}
function New-ResultZip {$stamp=Get-Date -Format 'yyyyMMdd_HHmmss';$zip=Join-Path $repositoryRoot ("StarCluster_CP159_native_results_{0}.zip" -f $stamp);if(Test-Path $zip){Remove-Item -Force $zip};Compress-Archive -Path (Join-Path $outRoot '*') -DestinationPath $zip -CompressionLevel Optimal;return $zip}
$python=Get-Cpython313Command;$pythonVersion=& $python.Command @($python.Args+@('--version')) 2>&1|Out-String;$dotnetVersion=(& dotnet --version 2>&1|Out-String).Trim();if($LASTEXITCODE -ne 0 -or $dotnetVersion -ne '8.0.423'){throw "CP159 requires .NET SDK 8.0.423 exactly; observed '$dotnetVersion'."};Write-Host("CP159 runtimes: {0}; .NET SDK {1}; jobs {2}" -f $pythonVersion.Trim(),$dotnetVersion,$Jobs);Invoke-PythonChecked $python @('-B',$preflight,'--repo',$repositoryRoot) 'CP159 preflight failed'
if($RepositoryOnly){if(-not $NoClean -and (Test-Path $outRoot)){Remove-Item -Recurse -Force $outRoot};New-Item -ItemType Directory -Force -Path $outRoot,$testOut,$parityOut,$deterministicOut,$tl1PhaseAOut|Out-Null;Push-Location $repositoryRoot;try{
 Write-Host '[1/8] Python research regression (604 tests)...';Invoke-PythonResearchTests
 Write-Host '[2/8] Warning-as-error .NET build...';Invoke-Captured 'CP159 build' (Join-Path $outRoot 'build.log'){dotnet build StarCluster.sln --configuration Release --nologo -warnaserror}
 Write-Host '[3/8] xUnit + ScenarioRunner regression...';dotnet test tests\StarCluster.Tests\StarCluster.Tests.csproj --configuration Release --no-build --nologo --logger 'trx;LogFileName=cp159-tests.trx' --results-directory $testOut;$xunitExit=$LASTEXITCODE;[xml]$trx=Get-Content -LiteralPath (Join-Path $testOut 'cp159-tests.trx') -Raw;$c=$trx.TestRun.ResultSummary.Counters;$total=[int]$c.total;$passed=[int]$c.passed;$failed=[int]$c.failed;$skipped=[int]$c.notExecuted;if($xunitExit -ne 0 -or $total -ne 934 -or $passed -ne 934 -or $failed -ne 0 -or $skipped -ne 0){throw 'CP159 xUnit mismatch.'};$selfLog=Join-Path $outRoot 'scenario-self-tests.log';Invoke-Captured 'CP159 ScenarioRunner self-tests' $selfLog {dotnet run --project src\StarCluster.ScenarioRunner\StarCluster.ScenarioRunner.csproj --configuration Release --no-build -- self-test};if((Get-Content $selfLog -Raw)-notmatch 'Runner self-tests:\s+70 passed,\s+0 failed,\s+70 total\.'){throw 'CP159 expected 70/70 self-tests.'};Invoke-Captured 'CP159 deterministic scenarios' (Join-Path $outRoot 'deterministic-scenarios.log'){dotnet run --project src\StarCluster.ScenarioRunner\StarCluster.ScenarioRunner.csproj --configuration Release --no-build -- run-all --output-dir $deterministicOut};Invoke-Captured 'CP159 TL1 Phase-A' (Join-Path $outRoot 'tl1-phase-a.log'){dotnet run --project src\StarCluster.ScenarioRunner\StarCluster.ScenarioRunner.csproj --configuration Release --no-build -- tl1-phase-a --output-dir $tl1PhaseAOut}
 Write-Host '[4/8] C#/Python parity...';Invoke-PythonChecked $python @('-B',$research,'--repo',$repositoryRoot,'parity','--output-dir',$parityOut) 'CP159 parity failed';$parity=Read-Json (Join-Path $parityOut 'summary.json');if(-not[bool]$parity.passed -or [int]$parity.cases -ne 25){throw 'CP159 parity mismatch.'}
 Write-Host '[5/8] CP159 focused AUX closure tests...';$sim=Join-Path $repositoryRoot 'tools\simulation';$oldPath=$env:PYTHONPATH;try{if([string]::IsNullOrWhiteSpace($oldPath)){$env:PYTHONPATH=$sim}else{$env:PYTHONPATH=$sim+[IO.Path]::PathSeparator+$oldPath};& $python.Command @($python.Args+@('-B','-m','unittest','discover','-v','-s','tools/simulation/tests','-p','test_cp159_*.py'));if($LASTEXITCODE -ne 0){throw 'CP159 focused tests failed.'}}finally{$env:PYTHONPATH=$oldPath}
 Write-Host '[6/8] CP159 PF3 conformance + focused closure plan...';Invoke-AuxChecked @('plan','--out',$planOut) 'CP159 plan failed';$pl=Read-Json (Join-Path $planOut 'summary.json');if([int]$pl.fieldCandidateTlPoints -ne 99 -or [int]$pl.crystallineCandidateTlPoints -ne 40 -or [int64]$pl.substantiveCombatTrials -ne 3390000 -or [int64]$pl.repairDroneMicroTrials -ne 1728000){throw 'CP159 plan mismatch.'};Copy-Pf3Snapshot
 Write-Host '[7/8] CP159 live specialist/Drone architecture smoke...';Invoke-AuxChecked @('smoke','--out',$smokeOut) 'CP159 smoke failed';$sm=Read-Json (Join-Path $smokeOut 'summary.json');if(-not[bool]$sm.passed -or [int]$sm.combatTrials -ne 2 -or [int]$sm.microProbes -ne 1){throw 'CP159 smoke mismatch.'}
 Write-Host '[8/8] Writing RepositoryOnly acceptance...';$bm=Read-Json (Join-Path $repositoryRoot 'docs\validation\evidence\checkpoint-159\research_execution_baseline_manifest_v0_3.json');$summary=[ordered]@{schemaVersion='star-cluster-cp159-repository-only-acceptance-v0.1';checkpoint=159;repositoryOnly=$true;failedGates=@();python=$pythonVersion.Trim();dotnetSdk=$dotnetVersion;buildPassed=$true;pythonTestsPassed=604;xunitTotal=$total;xunitPassed=$passed;xunitFailed=$failed;xunitSkipped=$skipped;scenarioRunnerSelfTestsPassed=70;deterministicScenarioCorpusPassed=$true;tl1PhaseACorpusPassed=$true;researchParityPassed=25;cp159FocusedTestsPassed=30;pendingFinalizationBaselineId='CP159-PF3';pendingFinalizationMatrixSha256=$bm.materializedMatrixSha256;cp158AuxPendingFinalizationPromotionCompleted=$true;productionAuthorityChanged=$false;architectureSmokeCombats=2;architectureSmokeMicroProbes=1;fieldCandidateTlPoints=99;crystallineCandidateTlPoints=40;repairDroneCandidateTlPoints=48;plannedSubstantiveCombatTrials=3390000;plannedRepairDroneMicroTrials=1728000;substantiveCombatTrials=0;repairDroneMicroTrials=0;tuningAllowed=$false;automaticPostStudyPromotion=$false;nextPass='zero-combat PF4 AUX closure promotion if specialist closure succeeds';finalMajorPass='Reactor/TP Scarcity and Whole-Ship Equilibrium'};$summary|ConvertTo-Json -Depth 8|Set-Content $repoOnlySummary -Encoding UTF8;Invoke-PythonChecked $python @('-B',$contract,'--repo',$repositoryRoot,'--native-results',$outRoot) 'CP159 RepositoryOnly contract failed';Write-Host 'CP159 RepositoryOnly PASSED. Run again without -RepositoryOnly to execute/resume 3,390,000 specialist/headroom combats plus 1,728,000 Damage-Control Drone microtrials.' -ForegroundColor Green
 }finally{Pop-Location};exit 0}
if(-not(Test-Path $repoOnlySummary)){throw 'Run CP159 -RepositoryOnly first in this same extraction.'};Push-Location $repositoryRoot;try{
 Write-Host '[final 1/9] Revalidating repository, PF3, and RepositoryOnly state...';Invoke-PythonChecked $python @('-B',$preflight,'--repo',$repositoryRoot) 'CP159 final preflight failed';Invoke-PythonChecked $python @('-B',$contract,'--repo',$repositoryRoot,'--native-results',$outRoot) 'CP159 RepositoryOnly state contract failed'
 Write-Host '[final 2/9] Executing/resuming matched PF3 baseline (120,000)...';$sum=Join-Path $baselineOut 'summary.json';if(Valid-Summary $sum 'baseline' 120000){Write-Host '       CP159 baseline valid; reusing.'}else{if(Test-Path $baselineOut){Remove-Item -Recurse -Force $baselineOut};Invoke-AuxChecked @('baseline','--out',$baselineOut,'--jobs',[string]$Jobs) 'CP159 baseline failed'}
 Write-Host '[final 3/9] Executing/resuming Field Stabilizer high-SPEN screen (891,000)...';New-Item -ItemType Directory -Force -Path $fieldScreenRoot|Out-Null;foreach($tl in 7,8,9){$dir=Join-Path $fieldScreenRoot ("TL{0}" -f $tl);$sum=Join-Path $dir 'summary.json';if(Valid-Summary $sum 'field-screen' 297000){Write-Host("       Field TL{0} valid; reusing." -f $tl)}else{if(Test-Path $dir){Remove-Item -Recurse -Force $dir};Invoke-AuxChecked @('field-screen','--out',$dir,'--tl',[string]$tl,'--jobs',[string]$Jobs) "CP159 Field Stabilizer TL$tl failed"}};if(Test-Path $fieldMerged){Remove-Item -Recurse -Force $fieldMerged};Invoke-AuxChecked @('merge-field','--baseline',(Join-Path $baselineOut 'context_results.csv'),'--batches',$fieldScreenRoot,'--out',$fieldMerged) 'CP159 Field screen merge failed';$fs=Read-Json (Join-Path $fieldMerged 'summary.json');if([int64]$fs.combatTrials -ne 891000 -or [int]$fs.candidates -ne 99 -or [int]$fs.errorTrials -ne 0){throw 'CP159 Field screen merged scale mismatch.'}
 Write-Host '[final 4/9] Executing/resuming Crystalline TL8-TL9 headroom screen (960,000)...';New-Item -ItemType Directory -Force -Path $crystalScreenRoot|Out-Null;foreach($tl in 8,9){$dir=Join-Path $crystalScreenRoot ("TL{0}" -f $tl);$sum=Join-Path $dir 'summary.json';if(Valid-Summary $sum 'crystal-screen' 480000){Write-Host("       Crystalline TL{0} valid; reusing." -f $tl)}else{if(Test-Path $dir){Remove-Item -Recurse -Force $dir};Invoke-AuxChecked @('crystal-screen','--out',$dir,'--tl',[string]$tl,'--jobs',[string]$Jobs) "CP159 Crystalline TL$tl failed"}};if(Test-Path $crystalMerged){Remove-Item -Recurse -Force $crystalMerged};Invoke-AuxChecked @('merge-crystal','--baseline',(Join-Path $baselineOut 'context_results.csv'),'--batches',$crystalScreenRoot,'--out',$crystalMerged) 'CP159 Crystalline screen merge failed';$cs=Read-Json (Join-Path $crystalMerged 'summary.json');if([int64]$cs.combatTrials -ne 960000 -or [int]$cs.candidates -ne 40 -or [int]$cs.errorTrials -ne 0){throw 'CP159 Crystalline screen merged scale mismatch.'}
 Write-Host '[final 5/9] Executing/resuming Field Stabilizer deep confirmation (378,000)...';$sum=Join-Path $fieldDeepOut 'summary.json';if((Valid-Summary $sum 'field-deep' 378000) -and (Valid-Summary (Join-Path $fieldDeepOut 'merged\summary.json') 'field-deep-merged' 378000)){Write-Host '       Field deep valid; reusing.'}else{if(Test-Path $fieldDeepOut){Remove-Item -Recurse -Force $fieldDeepOut};Invoke-AuxChecked @('field-deep','--out',$fieldDeepOut,'--jobs',[string]$Jobs) 'CP159 Field deep failed'};$fd=Read-Json (Join-Path $fieldDeepOut 'merged\summary.json');if([int64]$fd.combatTrials -ne 378000 -or [int]$fd.packages -ne 7 -or [int]$fd.errorTrials -ne 0){throw 'CP159 Field deep merge mismatch.'}
 Write-Host '[final 6/9] Executing/resuming Crystalline deep confirmation (960,000)...';$sum=Join-Path $crystalDeepOut 'summary.json';if((Valid-Summary $sum 'crystal-deep' 960000) -and (Valid-Summary (Join-Path $crystalDeepOut 'merged\summary.json') 'crystal-deep-merged' 960000)){Write-Host '       Crystalline deep valid; reusing.'}else{if(Test-Path $crystalDeepOut){Remove-Item -Recurse -Force $crystalDeepOut};Invoke-AuxChecked @('crystal-deep','--out',$crystalDeepOut,'--jobs',[string]$Jobs) 'CP159 Crystalline deep failed'};$cd=Read-Json (Join-Path $crystalDeepOut 'merged\summary.json');if([int64]$cd.combatTrials -ne 960000 -or [int]$cd.packages -ne 6 -or [int]$cd.errorTrials -ne 0){throw 'CP159 Crystalline deep merge mismatch.'}
 Write-Host '[final 7/9] Executing/resuming Field Stabilizer x Shield Hardener interactions (81,000)...';$sum=Join-Path $interactionOut 'summary.json';if(Valid-Summary $sum 'field-hardener-interaction' 81000){Write-Host '       Field/Hardener interactions valid; reusing.'}else{if(Test-Path $interactionOut){Remove-Item -Recurse -Force $interactionOut};Invoke-AuxChecked @('field-hardener-interactions','--out',$interactionOut,'--jobs',[string]$Jobs) 'CP159 Field/Hardener interactions failed'}
 Write-Host '[final 8/9] Executing/resuming Damage-Control Drone kit-endurance microstudy (1,728,000)...';$sum=Join-Path $droneOut 'summary.json';if(Valid-Summary $sum 'repair-drone-micro' 1728000 'microTrials'){Write-Host '       Repair Drone microstudy valid; reusing.'}else{if(Test-Path $droneOut){Remove-Item -Recurse -Force $droneOut};Invoke-AuxChecked @('repair-drone-micro','--out',$droneOut,'--jobs',[string]$Jobs) 'CP159 Repair Drone microstudy failed'}
 Write-Host '[final 9/9] Writing final acceptance and packaging results...';$bs=Read-Json (Join-Path $baselineOut 'summary.json');$fs=Read-Json (Join-Path $fieldMerged 'summary.json');$cs=Read-Json (Join-Path $crystalMerged 'summary.json');$fd=Read-Json (Join-Path $fieldDeepOut 'merged\summary.json');$cd=Read-Json (Join-Path $crystalDeepOut 'merged\summary.json');$is=Read-Json (Join-Path $interactionOut 'summary.json');$dm=Read-Json (Join-Path $droneOut 'summary.json');$ro=Read-Json $repoOnlySummary;$caps=[int64]$bs.turnCapSentinels+[int64]$fs.turnCapSentinels+[int64]$cs.turnCapSentinels+[int64]$fd.turnCapSentinels+[int64]$cd.turnCapSentinels+[int64]$is.turnCapSentinels;$errors=[int64]$bs.errors+[int64]$fs.errorTrials+[int64]$cs.errorTrials+[int64]$fd.errorTrials+[int64]$cd.errorTrials+[int64]$is.errors;$final=[ordered]@{};$ro.psobject.Properties|ForEach-Object{$final[$_.Name]=$_.Value};$final['schemaVersion']='star-cluster-cp159-native-acceptance-v0.1';$final['repositoryOnly']=$false;$final['repositoryOnlyAccepted']=$true;$final['baselineCombatTrials']=[int64]$bs.combatTrials;$final['fieldScreenCombatTrials']=[int64]$fs.combatTrials;$final['crystallineScreenCombatTrials']=[int64]$cs.combatTrials;$final['fieldDeepCombatTrials']=[int64]$fd.combatTrials;$final['crystallineDeepCombatTrials']=[int64]$cd.combatTrials;$final['fieldHardenerInteractionCombatTrials']=[int64]$is.combatTrials;$final['substantiveCombatTrials']=[int64]$bs.combatTrials+[int64]$fs.combatTrials+[int64]$cs.combatTrials+[int64]$fd.combatTrials+[int64]$cd.combatTrials+[int64]$is.combatTrials;$final['substantiveTurnCapSentinels']=$caps;$final['substantiveErrors']=$errors;$final['fieldDeepPackages']=[int]$fd.packages;$final['crystallineDeepPackages']=[int]$cd.packages;$final['fieldHardenerInteractionPackages']=[int]$is.packages;$final['repairDroneMicroTrials']=[int64]$dm.microTrials;$final['repairDroneSameTargetRerollAllowed']=[bool]$dm.sameTargetRerollAllowed;$final['repairDroneExtraKitMaximumEqualsDefault']=[bool]$dm.extraKitMaximumEqualsDefault;$final['automaticPostStudyPromotion']=$false;$final['productionAuthorityChanged']=$false;if([int64]$final['substantiveCombatTrials'] -ne 3390000 -or [int64]$final['repairDroneMicroTrials'] -ne 1728000 -or $errors -ne 0 -or $caps -ne 0){throw 'CP159 final substantive contract mismatch.'};$final|ConvertTo-Json -Depth 8|Set-Content $finalSummary -Encoding UTF8;Invoke-PythonChecked $python @('-B',$contract,'--repo',$repositoryRoot,'--native-results',$outRoot) 'CP159 final contract failed';$zip=New-ResultZip;Write-Host "CP159 native acceptance PASSED. Results: $zip" -ForegroundColor Green
}finally{Pop-Location}
