[CmdletBinding()]
param([switch]$RepositoryOnly,[switch]$NoClean,[int]$Jobs=24)
Set-StrictMode -Version 2.0
$ErrorActionPreference='Stop'
$repositoryRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path
$preflight=Join-Path $PSScriptRoot 'preflight_checkpoint_152.py'
$contract=Join-Path $PSScriptRoot 'test_checkpoint_152_contract.py'
$research=Join-Path $repositoryRoot 'tools\simulation\run_starcluster_research.py'
$study='docs/archive/testing/pre-cp165-active/cp152_direct_fire_joint_refinement_study_v0_1.json'
$cp139Study='docs/archive/testing/pre-cp165-active/cp139_def_res_reconciliation_study_v0_1.json'
$cp142Study='docs/archive/testing/pre-cp165-active/cp142_combat_surface_deep_reconciliation_study_v0_1.json'
$outRoot=Join-Path $repositoryRoot 'out\checkpoint-152'
$testOut=Join-Path $outRoot 'xunit';$parityOut=Join-Path $outRoot 'research-parity';$deterministicOut=Join-Path $outRoot 'deterministic-scenarios';$tl1PhaseAOut=Join-Path $outRoot 'tl1-phase-a';$cp139Out=Join-Path $outRoot 'cp139-reconciliation';$cp142Out=Join-Path $outRoot 'cp142-reconciliation-audit'
$planOut=Join-Path $outRoot 'direct-fire-plan';$smokeRoot=Join-Path $outRoot 'direct-fire-smoke';$kBatchRoot=Join-Path $outRoot 'direct-fire-k-batches';$eBatchRoot=Join-Path $outRoot 'direct-fire-e-batches';$kMerge=Join-Path $outRoot 'direct-fire-k-merged';$eMerge=Join-Path $outRoot 'direct-fire-e-merged';$jointSelect=Join-Path $outRoot 'direct-fire-joint-select';$jointBatchRoot=Join-Path $outRoot 'direct-fire-joint-batches';$jointMerge=Join-Path $outRoot 'direct-fire-joint-merged'
$repoOnlySummary=Join-Path $outRoot 'CP152_REPOSITORY_ONLY_ACCEPTANCE.json';$finalSummary=Join-Path $outRoot 'CP152_NATIVE_ACCEPTANCE_SUMMARY.json'
$contextCounts=@{1=200;2=300;3=300;4=300;5=300;6=300;7=300;8=300;9=300}
function Get-Cpython313Command {$c=@(@{Command='py';Args=@('-3.13')},@{Command='python';Args=@()},@{Command='python3';Args=@()});foreach($x in $c){if(Get-Command $x.Command -ErrorAction SilentlyContinue){$v=& $x.Command @($x.Args+@('--version')) 2>&1|Out-String;if($LASTEXITCODE -eq 0 -and $v -match 'Python\s+3\.13(?:\.|\s|$)'){return $x}}};throw 'CP152 requires Python 3.13.'}
function Invoke-PythonChecked([object]$Python,[string[]]$Arguments,[string]$Failure){& $Python.Command @($Python.Args+$Arguments);if($LASTEXITCODE -ne 0){throw "$Failure (exit code $LASTEXITCODE)."}}
function Invoke-Captured([string]$Label,[string]$LogPath,[scriptblock]$Body){& $Body *> $LogPath;$e=$LASTEXITCODE;if($e -ne 0){Write-Host "       $Label output tail:" -ForegroundColor Yellow;Get-Content -LiteralPath $LogPath -Tail 120|ForEach-Object{Write-Host("       $_")};throw "$Label failed (exit code $e)."}}
function Read-Json([string]$Path){return(Get-Content -LiteralPath $Path -Raw|ConvertFrom-Json)}
function Relative-To-Repo([string]$Path){$root=[IO.Path]::GetFullPath($repositoryRoot);$full=[IO.Path]::GetFullPath($Path);$sep=[IO.Path]::DirectorySeparatorChar;$prefix=$root;if(-not $prefix.EndsWith([string]$sep)){$prefix+=$sep};if(-not $full.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){throw "Path outside repository: $Path"};return $full.Substring($prefix.Length)}
function Invoke-PythonWithSimulationPath([scriptblock]$Body){$sim=Join-Path $repositoryRoot 'tools\simulation';$old=$env:PYTHONPATH;try{if([string]::IsNullOrWhiteSpace($old)){$env:PYTHONPATH=$sim}else{$env:PYTHONPATH=$sim+[IO.Path]::PathSeparator+$old};& $Body}finally{$env:PYTHONPATH=$old}}
function Invoke-PythonFocusedPattern([string]$Pattern,[string]$Failure){Invoke-PythonWithSimulationPath {& $python.Command @($python.Args+@('-B','-m','unittest','discover','-v','-s','tools/simulation/tests','-p',$Pattern));if($LASTEXITCODE -ne 0){throw $Failure}}}
function Invoke-PythonResearchTests {$files=Get-ChildItem -LiteralPath (Join-Path $repositoryRoot 'tools\simulation\tests') -Filter 'test_*.py'|Sort-Object Name;if($files.Count -ne 43){throw "CP152 expected 43 Python modules, found $($files.Count)."};$chunks=@(@($files[0..12]),@($files[13..18]),@($files[19..24]),@($files[25..38]),@($files[39]),@($files[40]),@($files[41]),@($files[42]));Invoke-PythonWithSimulationPath {for($i=0;$i -lt $chunks.Count;$i++){$mods=@($chunks[$i]|ForEach-Object{"tools.simulation.tests.$($_.BaseName)"});Write-Host("       Python test chunk {0}/8 ({1} modules)..." -f ($i+1),$mods.Count);& $python.Command @($python.Args+@('-B','-m','unittest')+$mods);if($LASTEXITCODE -ne 0){throw "CP152 Python chunk $($i+1) failed."}}}}
function Invoke-Plan {if(Test-Path $planOut){Remove-Item -Recurse -Force $planOut};New-Item -ItemType Directory -Force -Path $planOut|Out-Null;$rel=Relative-To-Repo $planOut;Invoke-Captured 'CP152 plan' (Join-Path $planOut 'console.log') {& $python.Command @($python.Args+@('-B',$research,'--repo',$repositoryRoot,'direct-fire-refinement-plan',$study,'--output-dir',$rel))};$s=Read-Json(Join-Path $planOut 'summary.json');if(-not[bool]$s.passed -or[int]$s.kTlCandidates -ne 2187 -or[int]$s.eTlCandidates -ne 2187 -or[int64]$s.totalCombatTrials -ne 48195000 -or[int64]$s.smokeCombatTrials -ne 218700){throw 'CP152 plan mismatch.'};return $s}
function Invoke-Smoke {$total=[int64]0;$caps=[int64]0;foreach($lane in @('K','E')){for($tl=1;$tl -le 9;$tl++){$dir=Join-Path $smokeRoot ("{0}\tl{1:D2}" -f $lane,$tl);if(Test-Path $dir){Remove-Item -Recurse -Force $dir};New-Item -ItemType Directory -Force -Path $dir|Out-Null;$rel=Relative-To-Repo $dir;Write-Host("       CP152 smoke {0} TL{1}: 243 x 50 = 12,150 combats" -f $lane,$tl);Invoke-Captured "CP152 smoke $lane TL$tl" (Join-Path $dir 'console.log') {& $python.Command @($python.Args+@('-B',$research,'--repo',$repositoryRoot,'direct-fire-refinement-sweep',$study,'--lane',$lane,'--output-dir',$rel,'--jobs',$Jobs,'--tl',$tl,'--candidate-start','0','--candidate-end','243','--trials','1','--smoke-panel'))};$s=Read-Json(Join-Path $dir 'summary.json');if(-not[bool]$s.passed -or[int]$s.combatTrials -ne 12150 -or[int]$s.errors -ne 0){throw "CP152 smoke $lane TL$tl mismatch."};$total+=[int64]$s.combatTrials;$caps+=[int64]$s.turnCapSentinels}};if($total -ne 218700){throw "CP152 smoke total $total."};return [pscustomobject]@{combatTrials=$total;turnCaps=$caps}}
function Test-LaneBatch([string]$Lane,[string]$Dir,[int]$Tl,[int]$Start,[int]$End,[int]$Trials){$sp=Join-Path $Dir 'summary.json';$rp=Join-Path $Dir ("direct_fire_{0}_candidate_context_results.csv" -f $Lane.ToLower());if(-not(Test-Path $sp)-or-not(Test-Path $rp)){return $false};try{$s=Read-Json $sp;$contexts=[int]$contextCounts[$Tl];$n=$End-$Start;$rows=$n*$contexts;if(-not[bool]$s.passed -or[string]$s.lane -ne $Lane -or[int]$s.tl -ne $Tl -or[int]$s.candidateStart -ne $Start -or[int]$s.candidateEnd -ne $End -or[int]$s.candidateContextCells -ne $rows -or[int]$s.trialsPerContext -ne $Trials -or[int64]$s.combatTrials -ne ([int64]$rows*$Trials) -or[int]$s.errors -ne 0){return $false};return $true}catch{return $false}}
function Invoke-Lane([string]$Lane,[string]$BatchRoot,[string]$MergeRoot,[int]$Trials){New-Item -ItemType Directory -Force -Path $BatchRoot|Out-Null;if(Test-Path $MergeRoot){Remove-Item -Recurse -Force $MergeRoot};New-Item -ItemType Directory -Force -Path $MergeRoot|Out-Null;$batch=0;for($tl=1;$tl -le 9;$tl++){$start=0;while($start -lt 243){$end=[Math]::Min($start+16,243);$batch++;$dir=Join-Path $BatchRoot ("tl{0:D2}_{1:D3}_{2:D3}" -f $tl,$start,$end);if(Test-LaneBatch $Lane $dir $tl $start $end $Trials){Write-Host("       CP152 {0} batch {1}/144 TL{2} {3}-{4} valid; reusing." -f $Lane,$batch,$tl,$start,($end-1))}else{if(Test-Path $dir){Remove-Item -Recurse -Force $dir};New-Item -ItemType Directory -Force -Path $dir|Out-Null;$rel=Relative-To-Repo $dir;$combats=[int64]($end-$start)*[int]$contextCounts[$tl]*$Trials;Write-Host("       CP152 {0} batch {1}/144 TL{2} {3}-{4}: {5:N0} combats" -f $Lane,$batch,$tl,$start,($end-1),$combats);Invoke-Captured "CP152 $Lane TL$tl $start-$end" (Join-Path $dir 'console.log') {& $python.Command @($python.Args+@('-B',$research,'--repo',$repositoryRoot,'direct-fire-refinement-sweep',$study,'--lane',$Lane,'--output-dir',(Relative-To-Repo $dir),'--jobs',$Jobs,'--tl',$tl,'--candidate-start',$start,'--candidate-end',$end,'--trials',$Trials))};if(-not(Test-LaneBatch $Lane $dir $tl $start $end $Trials)){throw "CP152 $Lane batch failed validation."}};$start=$end}};if($batch -ne 144){throw "CP152 $Lane batch count $batch."};Invoke-Captured "CP152 $Lane merge" (Join-Path $MergeRoot 'console.log') {& $python.Command @($python.Args+@('-B',$research,'--repo',$repositoryRoot,'direct-fire-refinement-merge',$study,'--lane',$Lane,'--batch-root',(Relative-To-Repo $BatchRoot),'--output-dir',(Relative-To-Repo $MergeRoot)))};$s=Read-Json(Join-Path $MergeRoot 'summary.json');$expected=if($Lane -eq 'K'){15795000}else{31590000};if(-not[bool]$s.passed -or[int64]$s.combatTrials -ne $expected -or[int]$s.errorTrials -ne 0){throw "CP152 $Lane merge mismatch."};return $s}
function Test-JointBatch([string]$Dir,[int]$Tl){$sp=Join-Path $Dir 'summary.json';if(-not(Test-Path $sp)){return $false};try{$s=Read-Json $sp;return([bool]$s.passed -and[int]$s.tl -eq $Tl -and[int]$s.candidates -eq 9 -and[int]$s.contextsPerCandidate -eq 100 -and[int]$s.trialsPerContext -eq 100 -and[int]$s.combatTrials -eq 90000 -and[int]$s.errors -eq 0)}catch{return $false}}
function Invoke-Joint {if(Test-Path $jointSelect){Remove-Item -Recurse -Force $jointSelect};New-Item -ItemType Directory -Force -Path $jointSelect|Out-Null;Invoke-Captured 'CP152 joint shortlist selection' (Join-Path $jointSelect 'console.log') {& $python.Command @($python.Args+@('-B',$research,'--repo',$repositoryRoot,'direct-fire-joint-select',$study,'--k-merged',(Relative-To-Repo $kMerge),'--e-merged',(Relative-To-Repo $eMerge),'--output-dir',(Relative-To-Repo $jointSelect)))};$sel=Read-Json(Join-Path $jointSelect 'summary.json');if(-not[bool]$sel.passed -or[int]$sel.jointTlCandidates -ne 81){throw 'CP152 joint selection mismatch.'};$ledger=Join-Path $jointSelect 'direct_fire_joint_candidate_ledger.csv';New-Item -ItemType Directory -Force -Path $jointBatchRoot|Out-Null;for($tl=1;$tl -le 9;$tl++){$dir=Join-Path $jointBatchRoot ("tl{0:D2}" -f $tl);if(Test-JointBatch $dir $tl){Write-Host("       CP152 joint TL{0} valid; reusing." -f $tl)}else{if(Test-Path $dir){Remove-Item -Recurse -Force $dir};New-Item -ItemType Directory -Force -Path $dir|Out-Null;Write-Host("       CP152 joint TL{0}: 9 x 100 contexts x 100 trials = 90,000 combats" -f $tl);Invoke-Captured "CP152 joint TL$tl" (Join-Path $dir 'console.log') {& $python.Command @($python.Args+@('-B',$research,'--repo',$repositoryRoot,'direct-fire-joint-sweep',$study,'--joint-ledger',(Relative-To-Repo $ledger),'--output-dir',(Relative-To-Repo $dir),'--jobs',$Jobs,'--tl',$tl,'--candidate-start','0','--candidate-end','9','--trials','100'))};if(-not(Test-JointBatch $dir $tl)){throw "CP152 joint TL$tl failed validation."}}};if(Test-Path $jointMerge){Remove-Item -Recurse -Force $jointMerge};New-Item -ItemType Directory -Force -Path $jointMerge|Out-Null;Invoke-Captured 'CP152 joint merge' (Join-Path $jointMerge 'console.log') {& $python.Command @($python.Args+@('-B',$research,'--repo',$repositoryRoot,'direct-fire-joint-merge',$study,'--joint-ledger',(Relative-To-Repo $ledger),'--batch-root',(Relative-To-Repo $jointBatchRoot),'--output-dir',(Relative-To-Repo $jointMerge)))};$s=Read-Json(Join-Path $jointMerge 'summary.json');if(-not[bool]$s.passed -or[int64]$s.jointCombatTrials -ne 810000 -or[int]$s.errorTrials -ne 0){throw 'CP152 joint merge mismatch.'};return $s}
function New-ResultZip {$stamp=Get-Date -Format 'yyyyMMdd_HHmmss';$zip=Join-Path $outRoot ("StarCluster_CP152_native_results_$stamp.zip");$stage=Join-Path $repositoryRoot 'out\checkpoint-152-package-staging';if(Test-Path $stage){Remove-Item -Recurse -Force $stage};New-Item -ItemType Directory -Force -Path $stage|Out-Null;foreach($item in Get-ChildItem -LiteralPath $outRoot -Force){if($item.FullName -eq $zip -or $item.Name -in @('direct-fire-k-batches','direct-fire-e-batches','direct-fire-joint-batches')){continue};Copy-Item -LiteralPath $item.FullName -Destination $stage -Recurse -Force};foreach($spec in @(@('K',$kBatchRoot),@('E',$eBatchRoot),@('J',$jointBatchRoot))){$dest=Join-Path $stage ("direct-fire-{0}-batch-summaries" -f $spec[0]);New-Item -ItemType Directory -Force -Path $dest|Out-Null;foreach($d in Get-ChildItem -LiteralPath $spec[1] -Directory|Sort-Object Name){$sp=Join-Path $d.FullName 'summary.json';if(Test-Path $sp){Copy-Item $sp (Join-Path $dest ($d.Name+'_summary.json')) -Force}}};Compress-Archive -Path (Join-Path $stage '*') -DestinationPath $zip -CompressionLevel Optimal;Remove-Item -Recurse -Force $stage;return $zip}
$python=Get-Cpython313Command;$pythonVersion=& $python.Command @($python.Args+@('--version')) 2>&1|Out-String;$dotnetVersion=(& dotnet --version 2>&1|Out-String).Trim();if($LASTEXITCODE -ne 0 -or $dotnetVersion -ne '8.0.423'){throw "CP152 requires .NET SDK 8.0.423 exactly; observed '$dotnetVersion'."};Write-Host("CP152 runtimes: {0}; .NET SDK {1}" -f $pythonVersion.Trim(),$dotnetVersion);Invoke-PythonChecked $python @('-B',$preflight,'--repo',$repositoryRoot) 'CP152 preflight failed'
if($RepositoryOnly){if(-not $NoClean -and(Test-Path $outRoot)){Remove-Item -Recurse -Force $outRoot};New-Item -ItemType Directory -Force -Path $outRoot,$testOut,$parityOut,$deterministicOut,$tl1PhaseAOut,$cp139Out,$cp142Out|Out-Null;Push-Location $repositoryRoot;try{
 Write-Host '[1/10] Python research tests (426 total)...';Invoke-PythonResearchTests
 Write-Host '[2/10] Warning-as-error .NET build...';Invoke-Captured 'CP152 build' (Join-Path $outRoot 'build.log') {dotnet build StarCluster.sln --configuration Release --nologo -warnaserror}
 Write-Host '[3/10] xUnit + ScenarioRunner deterministic corpora...';dotnet test tests\StarCluster.Tests\StarCluster.Tests.csproj --configuration Release --no-build --nologo --logger 'trx;LogFileName=cp152-tests.trx' --results-directory $testOut;$xunitExit=$LASTEXITCODE;[xml]$trx=Get-Content -LiteralPath (Join-Path $testOut 'cp152-tests.trx') -Raw;$c=$trx.TestRun.ResultSummary.Counters;$total=[int]$c.total;$passed=[int]$c.passed;$failed=[int]$c.failed;$skipped=[int]$c.notExecuted;if($xunitExit -ne 0 -or$total -ne 934 -or$passed -ne 934 -or$failed -ne 0 -or$skipped -ne 0){throw 'CP152 xUnit mismatch.'};$selfLog=Join-Path $outRoot 'scenario-self-tests.log';Invoke-Captured 'CP152 ScenarioRunner self-tests' $selfLog {dotnet run --project src\StarCluster.ScenarioRunner\StarCluster.ScenarioRunner.csproj --configuration Release --no-build -- self-test};if((Get-Content $selfLog -Raw)-notmatch 'Runner self-tests:\s+70 passed,\s+0 failed,\s+70 total\.'){throw 'CP152 expected 70/70 self-tests.'};Invoke-Captured 'CP152 deterministic scenarios' (Join-Path $outRoot 'deterministic-scenarios.log') {dotnet run --project src\StarCluster.ScenarioRunner\StarCluster.ScenarioRunner.csproj --configuration Release --no-build -- run-all --output-dir $deterministicOut};Invoke-Captured 'CP152 TL1 Phase-A' (Join-Path $outRoot 'tl1-phase-a.log') {dotnet run --project src\StarCluster.ScenarioRunner\StarCluster.ScenarioRunner.csproj --configuration Release --no-build -- tl1-phase-a --output-dir $tl1PhaseAOut}
 Write-Host '[4/10] C#/Python parity...';Invoke-PythonChecked $python @('-B',$research,'--repo',$repositoryRoot,'parity','--output-dir',$parityOut) 'CP152 parity failed';$parity=Read-Json(Join-Path $parityOut 'summary.json');if(-not[bool]$parity.passed -or[int]$parity.cases -ne 25){throw 'CP152 parity mismatch.'}
 Write-Host '[5/10] CP139 reconciliation foundation...';Invoke-PythonFocusedPattern 'test_cp139_def_res_reconciliation.py' 'CP139 focused failed';Invoke-PythonChecked $python @('-B',$research,'--repo',$repositoryRoot,'combat-model-reconciliation-study',$cp139Study,'--output-dir','out/checkpoint-152/cp139-reconciliation') 'CP139 reconciliation failed'
 Write-Host '[6/10] Focused CP140-CP152 tests...';foreach($p in @('test_cp140_stage_a_integration.py','test_cp141_combat_duration_stalemate.py','test_cp142_combat_surface_reconciliation.py','test_cp143_missile_mirror_pacing_attribution.py','test_cp144_*.py','test_cp145_*.py','test_cp146_*.py','test_cp147_*.py','test_cp148_*.py','test_cp149_*.py','test_cp150_*.py','test_cp151_*.py','test_cp152_*.py')){Invoke-PythonFocusedPattern $p "Focused regression failed: $p"}
 Write-Host '[7/10] CP142 reconciliation audit...';Invoke-PythonChecked $python @('-B',$research,'--repo',$repositoryRoot,'combat-surface-reconciliation-audit',$cp142Study,'--output-dir','out/checkpoint-152/cp142-reconciliation-audit') 'CP142 audit failed';$audit=Read-Json(Join-Path $cp142Out 'reconciliation_summary.json');if(-not[bool]$audit.passed -or[int]$audit.ledgerRows -ne 531 -or[int]$audit.changedVsCp141Rows -ne 72 -or[int]$audit.explicitUnresolvedRows -ne 7){throw 'CP142 audit mismatch.'}
 Write-Host '[8/10] CP152 48.195M direct-fire plan...';$plan=Invoke-Plan
 Write-Host '[9/10] CP152 all-candidate K/E smoke (218,700 combats)...';$smoke=Invoke-Smoke
 Write-Host '[10/10] Writing RepositoryOnly acceptance...';$summary=[ordered]@{schemaVersion='star-cluster-cp152-repository-only-acceptance-v0.1';checkpoint=152;repositoryOnly=$true;failedGates=@();python=$pythonVersion.Trim();dotnetSdk=$dotnetVersion;buildPassed=$true;pythonTestsPassed=426;xunitTotal=$total;xunitPassed=$passed;xunitFailed=$failed;xunitSkipped=$skipped;scenarioRunnerSelfTestsPassed=70;deterministicScenarioCorpusPassed=$true;tl1PhaseACorpusPassed=$true;researchParityPassed=25;cp139FocusedTestsPassed=9;cp140FocusedTestsPassed=10;cp141FocusedTestsPassed=10;cp142FocusedTestsPassed=12;cp143FocusedTestsPassed=12;cp144FocusedTestsPassed=11;cp145FocusedTestsPassed=12;cp146FocusedTestsPassed=18;cp147FocusedTestsPassed=18;cp148FocusedTestsPassed=12;cp149FocusedTestsPassed=16;cp150FocusedTestsPassed=16;cp151FocusedTestsPassed=18;cp152FocusedTestsPassed=18;acceptedCp151EvidenceHashLocked=$true;pointScale=2;combatDoctrine='cp147_tactical_utility';kTlCandidates=2187;eTlCandidates=2187;kCombatTrials=15795000;eCombatTrials=31590000;jointCombatTrials=810000;plannedSubstantiveCombatTrials=48195000;smokeCombatTrials=[int64]$smoke.combatTrials;smokeTurnCapSentinels=[int64]$smoke.turnCaps;smokeErrors=0;sourceMatrixUnmodified=$true;substantiveCombatTrials=0;tuningAllowed=$false;automaticPromotion=$false;stageBAutomatic=$false;nextStage='execute/resume CP152 K lane, E lane, then data-selected K/E joint confirmation'};$summary|ConvertTo-Json -Depth 8|Set-Content $repoOnlySummary -Encoding UTF8;Invoke-PythonChecked $python @('-B',$contract,'--repo',$repositoryRoot,'--native-results',$outRoot) 'CP152 RepositoryOnly contract failed';Write-Host 'CP152 RepositoryOnly PASSED. Run again without -RepositoryOnly to execute/resume 48.195M substantive combats.' -ForegroundColor Green
}finally{Pop-Location};exit 0}
if(-not(Test-Path $repoOnlySummary)){throw 'Run CP152 -RepositoryOnly first in this same extraction.'}
Push-Location $repositoryRoot;try{Write-Host '[final 1/5] Revalidating repository and RepositoryOnly state...';Invoke-PythonChecked $python @('-B',$preflight,'--repo',$repositoryRoot) 'CP152 final preflight failed';Invoke-PythonChecked $python @('-B',$contract,'--repo',$repositoryRoot,'--native-results',$outRoot) 'CP152 RepositoryOnly state contract failed';Write-Host '[final 2/5] Executing/resuming K completion lane (15.795M)...';$k=Invoke-Lane 'K' $kBatchRoot $kMerge 25;Write-Host '[final 3/5] Executing/resuming broad Energy lane (31.59M)...';$e=Invoke-Lane 'E' $eBatchRoot $eMerge 50;Write-Host '[final 4/5] Selecting and executing/resuming joint K/E confirmation (0.81M)...';$j=Invoke-Joint;Write-Host '[final 5/5] Final acceptance and result ZIP...';$ro=Read-Json $repoOnlySummary;$final=[ordered]@{};$ro.psobject.Properties|ForEach-Object{$final[$_.Name]=$_.Value};$final['schemaVersion']='star-cluster-cp152-native-acceptance-v0.1';$final['repositoryOnly']=$false;$final['repositoryOnlyAccepted']=$true;$final['substantiveSweepCompleted']=$true;$final['kSubstantiveCombatTrials']=[int64]$k.combatTrials;$final['eSubstantiveCombatTrials']=[int64]$e.combatTrials;$final['jointSubstantiveCombatTrials']=[int64]$j.jointCombatTrials;$final['substantiveCombatTrials']=[int64]$k.combatTrials+[int64]$e.combatTrials+[int64]$j.jointCombatTrials;$final['substantiveTurnCapSentinels']=[int64]$k.turnCapSentinels+[int64]$e.turnCapSentinels+[int64]$j.turnCapSentinels;$final['substantiveErrorTrials']=[int64]$k.errorTrials+[int64]$e.errorTrials+[int64]$j.errorTrials;$final['jointTlCandidates']=81;$final['nextStage']='analyze K/E response surfaces, Energy mode utilization, joint candidate interactions, and select coherent non-regressing direct-fire ladders before any source numerical promotion';$final|ConvertTo-Json -Depth 8|Set-Content $finalSummary -Encoding UTF8;Invoke-PythonChecked $python @('-B',$contract,'--repo',$repositoryRoot,'--native-results',$outRoot) 'CP152 final contract failed';$zip=New-ResultZip;Write-Host "CP152 native acceptance PASSED. Results: $zip" -ForegroundColor Green}finally{Pop-Location}
