namespace StarCluster.Core.Diagnostics;

/// <summary>
/// Stable categories written to the authoritative prototype event journal.
/// </summary>
public enum DiagnosticEventType
{
    SessionStarted,
    SessionEnded,
    ScenarioInitialized,
    ScenarioReset,
    TrackUpdated,
    SensorStateChanged,
    PhaseAdvanced,
    ShipMovementDestinationCommitted,
    ShipMovementStepResolved,
    ShipMovementResolved,
    DirectFireOrderCommitted,
    MissileLaunchResolved,
    MissileDatalinkUpdated,
    MissileLocalSensorUpdated,
    MissileGuidanceArbitrated,
    MissileGuidanceReplanned,
    MissileGuidanceStarted,
    MissileTerminalOpportunity,
    MissileSearchActivated,
    MissileTerminalAcquisitionResolved,
    MissileTerminalAttackResolved,
    MissileSelfDestructed,
    MissileMovementEdgeResolved,
    MissileMoved,
    MissileContactAcquired,
    MissileContactMaintained,
    MissileContactLost,
    ObservedTrailSegmentStarted,
    ObservedTrailSegmentExtended,
    ObservedTrailSegmentClosed,
    InterceptionTargetAcquired,
    MissileInterceptionAttempted,
    MissileGuidanceCompleted,
    MissileGuidanceResolved,
    MissileStackChanged,
    MissileBatchResolved,
    TacticalViewRefreshed,
    MissileBatchFinalizationFailed,
    MissileRouteProjected,
    TacticalFeedback,
    DamagePhaseEntered,
    DamageControlPhaseEntered,
    DiagnosticNote,
}
