[CmdletBinding()]
param([switch]$RepositoryOnly,[switch]$NoClean)
$ErrorActionPreference='Stop';$scriptRoot=Split-Path -Parent $MyInvocation.MyCommand.Path;$repo=(Resolve-Path (Join-Path $scriptRoot '..\..\..')).Path;$out=Join-Path $repo 'out\checkpoint-165';$research=Join-Path $repo 'tools\simulation\run_starcluster_research.py'
function Get-Cpython313Command {foreach($c in @(@{C='py';A=@('-3.13')},@{C='python';A=@()},@{C='python3';A=@()})){if(Get-Command $c.C -ErrorAction SilentlyContinue){$v=& $c.C @($c.A+@('--version')) 2>&1|Out-String;if($LASTEXITCODE -eq 0 -and $v -match 'Python\s+3\.13'){return $c}}};throw 'CP165 requires Python 3.13.'}
function PRun($py,[string[]]$a,$msg){& $py.C @($py.A+$a);if($LASTEXITCODE -ne 0){throw $msg}}
function J($p){Get-Content -LiteralPath $p -Raw|ConvertFrom-Json}
$py=Get-Cpython313Command;$dv=(& dotnet --version 2>&1|Out-String).Trim();if($dv -ne '8.0.423'){throw "CP165 requires .NET SDK 8.0.423; observed $dv"};PRun $py @('-B',(Join-Path $scriptRoot 'preflight_checkpoint_165.py'),'--repo',$repo) 'preflight failed'
if($RepositoryOnly){if(-not $NoClean -and(Test-Path $out)){Remove-Item -Recurse -Force $out};New-Item -ItemType Directory -Force -Path $out,(Join-Path $out 'xunit'),(Join-Path $out 'parity'),(Join-Path $out 'authority-snapshot')|Out-Null;Start-Transcript -Path (Join-Path $out 'CP165_console_output.txt') -Append|Out-Null;Push-Location $repo;try{
 $files=@(Get-ChildItem tools\simulation\tests -Filter 'test_*.py'|Sort-Object Name);if($files.Count-ne56){throw "expected 56 test modules"};$old=$env:PYTHONPATH;$env:PYTHONPATH=(Join-Path $repo 'tools\simulation');try{for($i=0;$i-lt$files.Count;$i+=8){$e=[Math]::Min($files.Count-1,$i+7);$mods=@($files[$i..$e]|%{"tools.simulation.tests.$($_.BaseName)"});& $py.C @($py.A+@('-B','-m','unittest')+$mods);if($LASTEXITCODE-ne0){throw 'Python regression failed'}}}finally{$env:PYTHONPATH=$old}
 dotnet build StarCluster.sln --configuration Release --nologo -warnaserror;if($LASTEXITCODE-ne0){throw 'build failed'}
 dotnet test tests\StarCluster.Tests\StarCluster.Tests.csproj --configuration Release --no-build --nologo --logger 'trx;LogFileName=cp165-tests.trx' --results-directory (Join-Path $out 'xunit');if($LASTEXITCODE-ne0){throw 'xunit failed'}
 [xml]$trx=Get-Content (Join-Path $out 'xunit\cp165-tests.trx') -Raw;$c=$trx.TestRun.ResultSummary.Counters;if([int]$c.total-ne934-or[int]$c.passed-ne934-or[int]$c.failed-ne0-or[int]$c.notExecuted-ne0){throw 'xunit count mismatch'}
 $self=dotnet run --project src\StarCluster.ScenarioRunner\StarCluster.ScenarioRunner.csproj --configuration Release --no-build -- self-test 2>&1|Out-String;if($LASTEXITCODE-ne0-or$self-notmatch '70 passed,\s+0 failed,\s+70 total'){throw 'self-test mismatch'};$self|Set-Content (Join-Path $out 'scenario-self-tests.log')
 dotnet run --project src\StarCluster.ScenarioRunner\StarCluster.ScenarioRunner.csproj --configuration Release --no-build -- run-all --output-dir (Join-Path $out 'deterministic-scenarios');if($LASTEXITCODE-ne0){throw 'deterministic corpus failed'}
 dotnet run --project src\StarCluster.ScenarioRunner\StarCluster.ScenarioRunner.csproj --configuration Release --no-build -- tl1-phase-a --output-dir (Join-Path $out 'tl1-phase-a');if($LASTEXITCODE-ne0){throw 'TL1 Phase-A failed'}
 PRun $py @('-B',$research,'--repo',$repo,'parity','--output-dir',(Join-Path $out 'parity')) 'parity failed';$par=J (Join-Path $out 'parity\summary.json');if(-not$par.passed-or[int]$par.cases-ne25){throw 'parity mismatch'}
 $old=$env:PYTHONPATH;$env:PYTHONPATH=(Join-Path $repo 'tools\simulation');try{& $py.C @($py.A+@('-B','-m','unittest','discover','-v','-s','tools/simulation/tests','-p','test_cp165_*.py'));if($LASTEXITCODE-ne0){throw 'CP165 focused tests failed'}}finally{$env:PYTHONPATH=$old}
 PRun $py @('-B',(Join-Path $scriptRoot 'document_authority_audit.py'),'--repo',$repo,'--out-dir',(Join-Path $out 'authority-snapshot')) 'authority audit failed';Copy-Item docs\design\player_technology\current_working_technology_baseline.json (Join-Path $out 'authority-snapshot')
 $s=[ordered]@{checkpoint=165;repositoryOnly=$true;failedGates=@();pythonTestsPassed=792;xunitPassed=934;xunitFailed=0;xunitSkipped=0;scenarioRunnerSelfTestsPassed=70;researchParityPassed=25;cp165FocusedTestsPassed=32;substantiveCombatTrials=0;documentationReconciliation=$true;productionRuntimeMechanicsChanged=$false;playerTechnologyRelocationEntries=116;testingFilesRelocated=92;wholeSystemIntegrationNext=$true};$s|ConvertTo-Json|Set-Content (Join-Path $out 'CP165_REPOSITORY_ONLY_ACCEPTANCE.json') -Encoding UTF8
 Write-Host 'CP165 RepositoryOnly PASSED.' -ForegroundColor Green
 }finally{Pop-Location};Stop-Transcript|Out-Null;exit 0}
if(-not(Test-Path (Join-Path $out 'CP165_REPOSITORY_ONLY_ACCEPTANCE.json'))){throw 'Run -RepositoryOnly first in the same extraction.'};Start-Transcript -Path (Join-Path $out 'CP165_console_output.txt') -Append|Out-Null;$s=J (Join-Path $out 'CP165_REPOSITORY_ONLY_ACCEPTANCE.json');$s.repositoryOnly=$false;$s|Add-Member -NotePropertyName repositoryOnlyAccepted -NotePropertyValue $true;$s|Add-Member -NotePropertyName studyCompleted -NotePropertyValue $true;$s|ConvertTo-Json|Set-Content (Join-Path $out 'CP165_NATIVE_ACCEPTANCE_SUMMARY.json') -Encoding UTF8;Stop-Transcript|Out-Null;$stamp=Get-Date -Format 'yyyyMMdd_HHmmss';$zip=Join-Path $repo "StarCluster_CP165_native_results_$stamp.zip";Compress-Archive -Path (Join-Path $out '*') -DestinationPath $zip -CompressionLevel Optimal;Write-Host "CP165 native acceptance PASSED. Results: $zip" -ForegroundColor Green
