[CmdletBinding()]
param([switch]$RepositoryOnly,[switch]$NoClean,[int]$Jobs=24)
$ErrorActionPreference='Stop'
$scriptRoot=Split-Path -Parent $MyInvocation.MyCommand.Path
$repositoryRoot=(Resolve-Path (Join-Path $scriptRoot '..\..\..')).Path
$preflight=Join-Path $scriptRoot 'preflight_checkpoint_163.py'
$contract=Join-Path $scriptRoot 'test_checkpoint_163_contract.py'
$research=Join-Path $repositoryRoot 'tools\simulation\run_starcluster_research.py'
$study=Join-Path $repositoryRoot 'docs\archive\testing\pre-cp165-active\cp163_apu_maturation_and_stacking_resilience_study_v0_1.json'
$outRoot=Join-Path $repositoryRoot 'out\checkpoint-163'
$testOut=Join-Path $outRoot 'xunit';$parityOut=Join-Path $outRoot 'research-parity';$deterministicOut=Join-Path $outRoot 'deterministic-scenarios';$tl1PhaseAOut=Join-Path $outRoot 'tl1-phase-a'
$planOut=Join-Path $outRoot 'apu-maturation-plan';$smokeOut=Join-Path $outRoot 'apu-maturation-smoke';$staticOut=Join-Path $outRoot 'static-apu';$stochasticOut=Join-Path $outRoot 'stochastic-apu';$combatRoot=Join-Path $outRoot 'combat-batches';$combatMerged=Join-Path $outRoot 'combat-merged';$snapshotOut=Join-Path $outRoot 'pf4-snapshot'
$repoOnlySummary=Join-Path $outRoot 'CP163_REPOSITORY_ONLY_ACCEPTANCE.json';$finalSummary=Join-Path $outRoot 'CP163_NATIVE_ACCEPTANCE_SUMMARY.json';$transcriptPath=Join-Path $outRoot 'CP163_console_output.txt';$transcriptStarted=$false

function Get-Cpython313Command {
 foreach($c in @(@{Command='py';Args=@('-3.13')},@{Command='python';Args=@()},@{Command='python3';Args=@()})){
  if(Get-Command $c.Command -ErrorAction SilentlyContinue){$v=& $c.Command @($c.Args+@('--version')) 2>&1|Out-String;if($LASTEXITCODE -eq 0 -and $v -match 'Python\s+3\.13(?:\.|\s|$)'){return $c}}
 }
 throw 'CP163 requires Python 3.13.'
}
function Invoke-PythonChecked([object]$Python,[string[]]$Arguments,[string]$Failure){& $Python.Command @($Python.Args+$Arguments);if($LASTEXITCODE -ne 0){throw "$Failure (exit code $LASTEXITCODE)."}}
function Invoke-Captured([string]$Label,[string]$LogPath,[scriptblock]$Body){$old=$ErrorActionPreference;try{$ErrorActionPreference='Continue';& $Body *> $LogPath;$code=$LASTEXITCODE}finally{$ErrorActionPreference=$old};if($code -ne 0){Write-Host "       $Label output tail:" -ForegroundColor Yellow;Get-Content -LiteralPath $LogPath -Tail 120|ForEach-Object{Write-Host("       $_")};throw "$Label failed (exit code $code)."}}
function Read-Json([string]$Path){return(Get-Content -LiteralPath $Path -Raw|ConvertFrom-Json)}
function Invoke-ReactorChecked([string[]]$Arguments,[string]$Failure){$sim=Join-Path $repositoryRoot 'tools\simulation';$oldPath=$env:PYTHONPATH;try{if([string]::IsNullOrWhiteSpace($oldPath)){$env:PYTHONPATH=$sim}else{$env:PYTHONPATH=$sim+[IO.Path]::PathSeparator+$oldPath};& $python.Command @($python.Args+@('-B','-m','starcluster_research.apu_maturation_calibration','--repo',$repositoryRoot,'--study',$study)+$Arguments);if($LASTEXITCODE -ne 0){throw "$Failure (exit code $LASTEXITCODE)."}}finally{$env:PYTHONPATH=$oldPath}}
function Invoke-PythonResearchTests {
 $files=@(Get-ChildItem -LiteralPath (Join-Path $repositoryRoot 'tools\simulation\tests') -Filter 'test_*.py'|Sort-Object Name);if($files.Count -ne 54){throw "CP163 expected 54 Python modules, found $($files.Count)."}
 $sim=Join-Path $repositoryRoot 'tools\simulation';$oldPath=$env:PYTHONPATH;try{if([string]::IsNullOrWhiteSpace($oldPath)){$env:PYTHONPATH=$sim}else{$env:PYTHONPATH=$sim+[IO.Path]::PathSeparator+$oldPath};$chunkSize=8;$chunks=[Math]::Ceiling($files.Count/[double]$chunkSize);for($c=0;$c -lt $chunks;$c++){$start=$c*$chunkSize;$end=[Math]::Min($files.Count-1,$start+$chunkSize-1);$mods=@($files[$start..$end]|ForEach-Object{"tools.simulation.tests.$($_.BaseName)"});Write-Host("       Python test chunk {0}/{1} ({2} modules)..." -f ($c+1),$chunks,$mods.Count);& $python.Command @($python.Args+@('-B','-m','unittest')+$mods);if($LASTEXITCODE -ne 0){throw "CP163 Python chunk $($c+1) failed."}}}finally{$env:PYTHONPATH=$oldPath}
}
function Valid-Summary([string]$Path,[string]$Mode,[int64]$Expected=-1,[string]$Field='combatTrials'){if(-not(Test-Path $Path)){return $false};try{$s=Read-Json $Path;if(-not[bool]$s.passed -or [string]$s.mode -ne $Mode){return $false};if($Expected -ge 0 -and [int64]$s.$Field -ne $Expected){return $false};if($s.PSObject.Properties.Name -contains 'errorTrials' -and [int64]$s.errorTrials -ne 0){return $false};return $true}catch{return $false}}
function Copy-Pf4Snapshot {
 if(Test-Path $snapshotOut){Remove-Item -Recurse -Force $snapshotOut};New-Item -ItemType Directory -Force -Path $snapshotOut|Out-Null
 Copy-Item -LiteralPath (Join-Path $repositoryRoot 'docs\design\player_technology\technology_research_execution_baseline_pending_finalization_v0_4.json') -Destination $snapshotOut
 Copy-Item -LiteralPath (Join-Path $repositoryRoot 'docs\validation\evidence\checkpoint-160\research_execution_baseline_manifest_v0_4.json') -Destination $snapshotOut
 Copy-Item -LiteralPath (Join-Path $repositoryRoot 'docs\validation\evidence\checkpoint-160\pf4_conformance_report_v0_1.json') -Destination $snapshotOut
 Copy-Item -LiteralPath (Join-Path $repositoryRoot 'docs\validation\evidence\checkpoint-163\accepted-cp162\CP162_NATIVE_ACCEPTANCE_SUMMARY.json') -Destination $snapshotOut
 Copy-Item -LiteralPath (Join-Path $repositoryRoot 'docs\validation\evidence\checkpoint-163\accepted-cp162\CP162_NATIVE_RESULTS_ARCHIVE_SHA256.txt') -Destination $snapshotOut
 Copy-Item -LiteralPath (Join-Path $repositoryRoot 'docs\validation\evidence\checkpoint-163\cp163_apu_maturation_study_contract_v0_1.json') -Destination $snapshotOut
}
function Stop-TranscriptSafe {if($script:transcriptStarted){try{Stop-Transcript|Out-Null}catch{};$script:transcriptStarted=$false}}
function New-ResultZip {$stamp=Get-Date -Format 'yyyyMMdd_HHmmss';$zip=Join-Path $repositoryRoot ("StarCluster_CP163_native_results_{0}.zip" -f $stamp);if(Test-Path $zip){Remove-Item -Force $zip};Compress-Archive -Path (Join-Path $outRoot '*') -DestinationPath $zip -CompressionLevel Optimal;return $zip}

$python=Get-Cpython313Command;$pythonVersion=& $python.Command @($python.Args+@('--version')) 2>&1|Out-String;$dotnetVersion=(& dotnet --version 2>&1|Out-String).Trim();if($LASTEXITCODE -ne 0 -or $dotnetVersion -ne '8.0.423'){throw "CP163 requires .NET SDK 8.0.423 exactly; observed '$dotnetVersion'."}
if($RepositoryOnly -and -not $NoClean -and (Test-Path $outRoot)){Remove-Item -Recurse -Force $outRoot};New-Item -ItemType Directory -Force -Path $outRoot|Out-Null;Start-Transcript -Path $transcriptPath -Append|Out-Null;$transcriptStarted=$true
try{
 Write-Host("CP163 runtimes: {0}; .NET SDK {1}; jobs {2}" -f $pythonVersion.Trim(),$dotnetVersion,$Jobs);Invoke-PythonChecked $python @('-B',$preflight,'--repo',$repositoryRoot) 'CP163 preflight failed'
 if($RepositoryOnly){
  New-Item -ItemType Directory -Force -Path $testOut,$parityOut,$deterministicOut,$tl1PhaseAOut|Out-Null;Push-Location $repositoryRoot
  try{
   Write-Host '[1/10] Python research regression (728 tests)...';Invoke-PythonResearchTests
   Write-Host '[2/10] Warning-as-error .NET build...';Invoke-Captured 'CP163 build' (Join-Path $outRoot 'build.log'){dotnet build StarCluster.sln --configuration Release --nologo -warnaserror}
   Write-Host '[3/10] xUnit + ScenarioRunner regression...';dotnet test tests\StarCluster.Tests\StarCluster.Tests.csproj --configuration Release --no-build --nologo --logger 'trx;LogFileName=cp163-tests.trx' --results-directory $testOut;$xunitExit=$LASTEXITCODE;[xml]$trx=Get-Content -LiteralPath (Join-Path $testOut 'cp163-tests.trx') -Raw;$c=$trx.TestRun.ResultSummary.Counters;$total=[int]$c.total;$passed=[int]$c.passed;$failed=[int]$c.failed;$skipped=[int]$c.notExecuted;if($xunitExit -ne 0 -or $total -ne 934 -or $passed -ne 934 -or $failed -ne 0 -or $skipped -ne 0){throw 'CP163 xUnit mismatch.'}
   $selfLog=Join-Path $outRoot 'scenario-self-tests.log';Invoke-Captured 'CP163 ScenarioRunner self-tests' $selfLog {dotnet run --project src\StarCluster.ScenarioRunner\StarCluster.ScenarioRunner.csproj --configuration Release --no-build -- self-test};if((Get-Content $selfLog -Raw)-notmatch 'Runner self-tests:\s+70 passed,\s+0 failed,\s+70 total\.'){throw 'CP163 expected 70/70 self-tests.'};Invoke-Captured 'CP163 deterministic scenarios' (Join-Path $outRoot 'deterministic-scenarios.log'){dotnet run --project src\StarCluster.ScenarioRunner\StarCluster.ScenarioRunner.csproj --configuration Release --no-build -- run-all --output-dir $deterministicOut};Invoke-Captured 'CP163 TL1 Phase-A' (Join-Path $outRoot 'tl1-phase-a.log'){dotnet run --project src\StarCluster.ScenarioRunner\StarCluster.ScenarioRunner.csproj --configuration Release --no-build -- tl1-phase-a --output-dir $tl1PhaseAOut}
   Write-Host '[4/10] C#/Python parity...';Invoke-PythonChecked $python @('-B',$research,'--repo',$repositoryRoot,'parity','--output-dir',$parityOut) 'CP163 parity failed';$parity=Read-Json (Join-Path $parityOut 'summary.json');if(-not[bool]$parity.passed -or [int]$parity.cases -ne 25){throw 'CP163 parity mismatch.'}
   Write-Host '[5/10] CP163 focused Main/APU tests (36)...';$sim=Join-Path $repositoryRoot 'tools\simulation';$oldPath=$env:PYTHONPATH;try{if([string]::IsNullOrWhiteSpace($oldPath)){$env:PYTHONPATH=$sim}else{$env:PYTHONPATH=$sim+[IO.Path]::PathSeparator+$oldPath};& $python.Command @($python.Args+@('-B','-m','unittest','discover','-v','-s','tools/simulation/tests','-p','test_cp163_*.py'));if($LASTEXITCODE -ne 0){throw 'CP163 focused tests failed.'}}finally{$env:PYTHONPATH=$oldPath}
   Write-Host '[6/10] Exact joint Main/APU study plan...';if(Test-Path $planOut){Remove-Item -Recurse -Force $planOut};Invoke-ReactorChecked @('plan','--out',$planOut) 'CP163 plan failed';$pl=Read-Json (Join-Path $planOut 'summary.json');if([int]$pl.legalPoweredArchitectures -ne 22482 -or [int]$pl.stochasticVariants -ne 1152 -or [int64]$pl.stochasticTurnSamples -ne 5760000 -or [int]$pl.combatCells -ne 1152 -or [int64]$pl.combatTrials -ne 2304000){throw 'CP163 plan mismatch.'}
   Write-Host '[7/10] Live additive APU integration smoke...';if(Test-Path $smokeOut){Remove-Item -Recurse -Force $smokeOut};Invoke-ReactorChecked @('smoke','--out',$smokeOut) 'CP163 smoke failed';$sm=Read-Json (Join-Path $smokeOut 'summary.json');if(-not[bool]$sm.passed -or [int]$sm.probes -ne 6 -or [int]$sm.combatTrials -ne 2){throw 'CP163 smoke mismatch.'}
   Write-Host '[8/10] Exact unrestricted stack/Space/TP surfaces...';if(Test-Path $staticOut){Remove-Item -Recurse -Force $staticOut};Invoke-ReactorChecked @('static','--out',$staticOut) 'CP163 static analysis failed';$st=Read-Json (Join-Path $staticOut 'summary.json');if([int]$st.legalPoweredArchitectures -ne 22482 -or [int]$st.oneMainReactorArchitectures -ne 16741 -or [int]$st.uniqueTlLocalApuPoints -ne 16 -or [int]$st.legalStackSupportRows -ne 288 -or [int]$st.resilienceRows -ne 330){throw 'CP163 static analysis scale mismatch.'}
   Write-Host '[9/10] Freezing PF4 + accepted CP162 provenance snapshot...';Copy-Pf4Snapshot
   Write-Host '[10/10] Writing RepositoryOnly acceptance...';$summary=[ordered]@{schemaVersion='star-cluster-cp163-repository-only-acceptance-v0.1';checkpoint=163;repositoryOnly=$true;failedGates=@();python=$pythonVersion.Trim();dotnetSdk=$dotnetVersion;buildPassed=$true;pythonTestsPassed=728;xunitTotal=$total;xunitPassed=$passed;xunitFailed=$failed;xunitSkipped=$skipped;scenarioRunnerSelfTestsPassed=70;deterministicScenarioCorpusPassed=$true;tl1PhaseACorpusPassed=$true;researchParityPassed=25;cp163FocusedTestsPassed=36;acceptedBaseCheckpoint=162;pendingFinalizationBaselineId='CP160-PF4';pendingFinalizationMatrixSha256='7fd4dfbbe375586de2605361006db84b68f89767c76ba4b76da6cf5f48253155';productionAuthorityChanged=$false;conceptChanged=$false;tuningAllowed=$false;automaticPromotion=$false;mainReactorSpace=6;mainReactorOffsets='-1,0,+1 from PF4';apuSpace=2;apuTrajectoryCount=5;apuMaturationBounds='TL5,TL6,TL7,TL8';latePlus3BoundaryTls='TL8,TL9';installationCountCapImposed=$false;legalPoweredArchitectures=22482;oneMainReactorArchitectures=16741;uniqueTlLocalApuPoints=16;staticLegalStackSupportRows=288;staticResilienceRows=330;stochasticVariants=1152;plannedStochasticTurnSamples=5760000;combatContexts=384;combatCells=1152;plannedSubstantiveCombatTrials=2304000;architectureSmokeCombats=2;substantiveCombatTrials=0;stochasticTurnSamples=0;playerBaseCruiserEnvelopeRetained=$true;broadLegalEnvelopeRetained=$true;selectionDeferredToNextCheckpoint=$true};$summary|ConvertTo-Json -Depth 8|Set-Content $repoOnlySummary -Encoding UTF8;Invoke-PythonChecked $python @('-B',$contract,'--repo',$repositoryRoot,'--native-results',$outRoot) 'CP163 RepositoryOnly contract failed';Write-Host 'CP163 RepositoryOnly PASSED. Run again without -RepositoryOnly to execute/resume 5,760,000 tactical-demand samples and 2,304,000 full-map combat trials.' -ForegroundColor Green
  }finally{Pop-Location};Stop-TranscriptSafe;exit 0
 }
 if(-not(Test-Path $repoOnlySummary)){throw 'Run CP163 -RepositoryOnly first in this same extraction.'};Push-Location $repositoryRoot
 try{
  Write-Host '[final 1/5] Revalidating repository, PF4, CP162 provenance, and RepositoryOnly state...';Invoke-PythonChecked $python @('-B',$preflight,'--repo',$repositoryRoot) 'CP163 final preflight failed';Invoke-PythonChecked $python @('-B',$contract,'--repo',$repositoryRoot,'--native-results',$outRoot) 'CP163 RepositoryOnly state contract failed'
  Write-Host '[final 2/5] Executing/resuming APU maturation stochastic surface (5,760,000 turn samples)...';$sum=Join-Path $stochasticOut 'summary.json';if(Valid-Summary $sum 'stochastic' 5760000 'turnSamples'){Write-Host '       CP163 stochastic surface valid; reusing.'}else{if(Test-Path $stochasticOut){Remove-Item -Recurse -Force $stochasticOut};Invoke-ReactorChecked @('stochastic','--static-dir',$staticOut,'--out',$stochasticOut,'--jobs',[string]$Jobs) 'CP163 stochastic stack surface failed'}
  Write-Host '[final 3/5] Executing/resuming full-map Main/APU combat batches (2,304,000 total)...';New-Item -ItemType Directory -Force -Path $combatRoot|Out-Null;$expected=@{1=144000;2=144000;3=144000;4=144000;5=288000;6=288000;7=288000;8=432000;9=432000};foreach($tl in 1..9){$dir=Join-Path $combatRoot ("TL{0}" -f $tl);$sum=Join-Path $dir 'summary.json';$want=[int64]$expected[$tl];if(Valid-Summary $sum 'combat-batch' $want){Write-Host("       Combat TL{0} valid; reusing." -f $tl)}else{if(Test-Path $dir){Remove-Item -Recurse -Force $dir};Invoke-ReactorChecked @('combat-batch','--tl',[string]$tl,'--out',$dir,'--jobs',[string]$Jobs) "CP163 combat TL$tl failed"}}
  Write-Host '[final 4/5] Merging Main/APU combat response surface...';if(Test-Path $combatMerged){Remove-Item -Recurse -Force $combatMerged};Invoke-ReactorChecked @('merge-combat','--batches',$combatRoot,'--out',$combatMerged) 'CP163 combat merge failed';$cm=Read-Json (Join-Path $combatMerged 'summary.json');if(-not[bool]$cm.passed -or [int]$cm.batches -ne 9 -or [int]$cm.cells -ne 1152 -or [int64]$cm.combatTrials -ne 2304000 -or [int64]$cm.errorTrials -ne 0){throw 'CP163 merged combat contract mismatch.'}
  Write-Host '[final 5/5] Writing final diagnostic acceptance and packaging results...';$sd=Read-Json (Join-Path $stochasticOut 'summary.json');$ro=Read-Json $repoOnlySummary;$final=[ordered]@{};$ro.psobject.Properties|ForEach-Object{$final[$_.Name]=$_.Value};$final['schemaVersion']='star-cluster-cp163-native-acceptance-v0.1';$final['repositoryOnly']=$false;$final['repositoryOnlyAccepted']=$true;$final['stochasticTurnSamples']=[int64]$sd.turnSamples;$final['stochasticVariantsCompleted']=[int]$sd.variants;$final['substantiveCombatTrials']=[int64]$cm.combatTrials;$final['combatCellsCompleted']=[int]$cm.cells;$final['combatTurnCapSentinels']=[int64]$cm.turnCapSentinels;$final['combatErrorTrials']=[int64]$cm.errorTrials;$final['studyCompleted']=$true;$final['tuningAllowed']=$false;$final['automaticPromotion']=$false;$final['productionAuthorityChanged']=$false;$final['selectionDeferredToNextCheckpoint']=$true;if([int64]$final['stochasticTurnSamples'] -ne 5760000 -or [int64]$final['substantiveCombatTrials'] -ne 2304000 -or [int64]$final['combatErrorTrials'] -ne 0){throw 'CP163 final substantive scale/error mismatch.'};$final|ConvertTo-Json -Depth 8|Set-Content $finalSummary -Encoding UTF8;Invoke-PythonChecked $python @('-B',$contract,'--repo',$repositoryRoot,'--native-results',$outRoot) 'CP163 final contract failed'
 }finally{Pop-Location};Stop-TranscriptSafe;$zip=New-ResultZip;Write-Host "CP163 native acceptance PASSED. Results: $zip" -ForegroundColor Green
}finally{Stop-TranscriptSafe}
