[CmdletBinding()]
param([switch]$RepositoryOnly,[switch]$NoClean,[int]$Jobs=24)
$ErrorActionPreference='Stop'
$scriptRoot=Split-Path -Parent $MyInvocation.MyCommand.Path
$repositoryRoot=(Resolve-Path (Join-Path $scriptRoot '..\..\..')).Path
$preflight=Join-Path $scriptRoot 'preflight_checkpoint_158.py'
$contract=Join-Path $scriptRoot 'test_checkpoint_158_contract.py'
$research=Join-Path $repositoryRoot 'tools\simulation\run_starcluster_research.py'
$study=Join-Path $repositoryRoot 'docs\archive\testing\pre-cp165-active\cp158_defense_aux_lifetime_viability_study_v0_1.json'
$outRoot=Join-Path $repositoryRoot 'out\checkpoint-158'
$testOut=Join-Path $outRoot 'xunit';$parityOut=Join-Path $outRoot 'research-parity';$deterministicOut=Join-Path $outRoot 'deterministic-scenarios';$tl1PhaseAOut=Join-Path $outRoot 'tl1-phase-a'
$planOut=Join-Path $outRoot 'aux-plan';$smokeOut=Join-Path $outRoot 'aux-smoke';$baselineOut=Join-Path $outRoot 'aux-baseline';$screenRoot=Join-Path $outRoot 'aux-screen-batches';$screenMerged=Join-Path $outRoot 'aux-screen-merged';$ladderOut=Join-Path $outRoot 'aux-ladder-synthesis';$deepRoot=Join-Path $outRoot 'aux-deep-batches';$deepMerged=Join-Path $outRoot 'aux-deep-merged';$pairRoot=Join-Path $outRoot 'aux-pairwise-batches';$pairMerged=Join-Path $outRoot 'aux-pairwise-merged';$snapshotOut=Join-Path $outRoot 'pf2-snapshot'
$repoOnlySummary=Join-Path $outRoot 'CP158_REPOSITORY_ONLY_ACCEPTANCE.json';$finalSummary=Join-Path $outRoot 'CP158_NATIVE_ACCEPTANCE_SUMMARY.json'
function Get-Cpython313Command { foreach($c in @(@{Command='py';Args=@('-3.13')},@{Command='python';Args=@()},@{Command='python3';Args=@()})){if(Get-Command $c.Command -ErrorAction SilentlyContinue){$v=& $c.Command @($c.Args+@('--version')) 2>&1|Out-String;if($LASTEXITCODE -eq 0 -and $v -match 'Python\s+3\.13(?:\.|\s|$)'){return $c}}};throw 'CP158 requires Python 3.13.' }
function Invoke-PythonChecked([object]$Python,[string[]]$Arguments,[string]$Failure){& $Python.Command @($Python.Args+$Arguments);if($LASTEXITCODE -ne 0){throw "$Failure (exit code $LASTEXITCODE)."}}
function Invoke-Captured([string]$Label,[string]$LogPath,[scriptblock]$Body){$old=$ErrorActionPreference;try{$ErrorActionPreference='Continue';& $Body *> $LogPath;$code=$LASTEXITCODE}finally{$ErrorActionPreference=$old};if($code -ne 0){Write-Host "       $Label output tail:" -ForegroundColor Yellow;Get-Content -LiteralPath $LogPath -Tail 120|ForEach-Object{Write-Host("       $_")};throw "$Label failed (exit code $code)."}}
function Read-Json([string]$Path){return(Get-Content -LiteralPath $Path -Raw|ConvertFrom-Json)}
function Invoke-AuxChecked([string[]]$Arguments,[string]$Failure){$sim=Join-Path $repositoryRoot 'tools\simulation';$oldPath=$env:PYTHONPATH;try{if([string]::IsNullOrWhiteSpace($oldPath)){$env:PYTHONPATH=$sim}else{$env:PYTHONPATH=$sim+[IO.Path]::PathSeparator+$oldPath};& $python.Command @($python.Args+@('-B','-m','starcluster_research.defense_aux_lifetime_viability','--repo',$repositoryRoot,'--study',$study)+$Arguments);if($LASTEXITCODE -ne 0){throw "$Failure (exit code $LASTEXITCODE)."}}finally{$env:PYTHONPATH=$oldPath}}
function Invoke-PythonResearchTests {$files=@(Get-ChildItem -LiteralPath (Join-Path $repositoryRoot 'tools\simulation\tests') -Filter 'test_*.py'|Sort-Object Name);if($files.Count -ne 49){throw "CP158 expected 49 Python modules, found $($files.Count)."};$sim=Join-Path $repositoryRoot 'tools\simulation';$oldPath=$env:PYTHONPATH;try{if([string]::IsNullOrWhiteSpace($oldPath)){$env:PYTHONPATH=$sim}else{$env:PYTHONPATH=$sim+[IO.Path]::PathSeparator+$oldPath};$chunkSize=8;$chunks=[Math]::Ceiling($files.Count/[double]$chunkSize);for($c=0;$c -lt $chunks;$c++){$start=$c*$chunkSize;$end=[Math]::Min($files.Count-1,$start+$chunkSize-1);$mods=@($files[$start..$end]|ForEach-Object{"tools.simulation.tests.$($_.BaseName)"});Write-Host("       Python test chunk {0}/{1} ({2} modules)..." -f ($c+1),$chunks,$mods.Count);& $python.Command @($python.Args+@('-B','-m','unittest')+$mods);if($LASTEXITCODE -ne 0){throw "CP158 Python chunk $($c+1) failed."}}}finally{$env:PYTHONPATH=$oldPath}}
function Valid-Summary([string]$Path,[string]$Mode,[int64]$CombatTrials=-1){if(-not(Test-Path $Path)){return $false};try{$s=Read-Json $Path;if(-not[bool]$s.passed -or [string]$s.mode -ne $Mode){return $false};if($CombatTrials -ge 0 -and [int64]$s.combatTrials -ne $CombatTrials){return $false};if($s.PSObject.Properties.Name -contains 'errors' -and [int]$s.errors -ne 0){return $false};if($s.PSObject.Properties.Name -contains 'errorTrials' -and [int]$s.errorTrials -ne 0){return $false};return $true}catch{return $false}}
function Copy-Pf2Snapshot {if(Test-Path $snapshotOut){Remove-Item -Recurse -Force $snapshotOut};New-Item -ItemType Directory -Force -Path $snapshotOut|Out-Null;$ev=Join-Path $repositoryRoot 'docs\validation\evidence\checkpoint-158';foreach($n in @('research_execution_baseline_manifest_v0_2.json','research_execution_baseline_diff_v0_2.csv','pf2_conformance_report_v0_1.json')){Copy-Item -LiteralPath (Join-Path $ev $n) -Destination $snapshotOut};Copy-Item -LiteralPath (Join-Path $repositoryRoot 'docs\archive\player_technology\pre-cp165-active\technology_research_execution_baseline_pending_finalization_v0_2.json') -Destination $snapshotOut}
function New-ResultZip {$stamp=Get-Date -Format 'yyyyMMdd_HHmmss';$zip=Join-Path $repositoryRoot ("StarCluster_CP158_native_results_{0}.zip" -f $stamp);if(Test-Path $zip){Remove-Item -Force $zip};Compress-Archive -Path (Join-Path $outRoot '*') -DestinationPath $zip -CompressionLevel Optimal;return $zip}
$python=Get-Cpython313Command;$pythonVersion=& $python.Command @($python.Args+@('--version')) 2>&1|Out-String;$dotnetVersion=(& dotnet --version 2>&1|Out-String).Trim();if($LASTEXITCODE -ne 0 -or $dotnetVersion -ne '8.0.423'){throw "CP158 requires .NET SDK 8.0.423 exactly; observed '$dotnetVersion'."};Write-Host("CP158 runtimes: {0}; .NET SDK {1}; jobs {2}" -f $pythonVersion.Trim(),$dotnetVersion,$Jobs);Invoke-PythonChecked $python @('-B',$preflight,'--repo',$repositoryRoot) 'CP158 preflight failed'
if($RepositoryOnly){if(-not $NoClean -and (Test-Path $outRoot)){Remove-Item -Recurse -Force $outRoot};New-Item -ItemType Directory -Force -Path $outRoot,$testOut,$parityOut,$deterministicOut,$tl1PhaseAOut|Out-Null;Push-Location $repositoryRoot;try{
 Write-Host '[1/8] Python research regression (574 tests)...';Invoke-PythonResearchTests
 Write-Host '[2/8] Warning-as-error .NET build...';Invoke-Captured 'CP158 build' (Join-Path $outRoot 'build.log'){dotnet build StarCluster.sln --configuration Release --nologo -warnaserror}
 Write-Host '[3/8] xUnit + ScenarioRunner regression...';dotnet test tests\StarCluster.Tests\StarCluster.Tests.csproj --configuration Release --no-build --nologo --logger 'trx;LogFileName=cp158-tests.trx' --results-directory $testOut;$xunitExit=$LASTEXITCODE;[xml]$trx=Get-Content -LiteralPath (Join-Path $testOut 'cp158-tests.trx') -Raw;$c=$trx.TestRun.ResultSummary.Counters;$total=[int]$c.total;$passed=[int]$c.passed;$failed=[int]$c.failed;$skipped=[int]$c.notExecuted;if($xunitExit -ne 0 -or $total -ne 934 -or $passed -ne 934 -or $failed -ne 0 -or $skipped -ne 0){throw 'CP158 xUnit mismatch.'};$selfLog=Join-Path $outRoot 'scenario-self-tests.log';Invoke-Captured 'CP158 ScenarioRunner self-tests' $selfLog {dotnet run --project src\StarCluster.ScenarioRunner\StarCluster.ScenarioRunner.csproj --configuration Release --no-build -- self-test};if((Get-Content $selfLog -Raw)-notmatch 'Runner self-tests:\s+70 passed,\s+0 failed,\s+70 total\.'){throw 'CP158 expected 70/70 self-tests.'};Invoke-Captured 'CP158 deterministic scenarios' (Join-Path $outRoot 'deterministic-scenarios.log'){dotnet run --project src\StarCluster.ScenarioRunner\StarCluster.ScenarioRunner.csproj --configuration Release --no-build -- run-all --output-dir $deterministicOut};Invoke-Captured 'CP158 TL1 Phase-A' (Join-Path $outRoot 'tl1-phase-a.log'){dotnet run --project src\StarCluster.ScenarioRunner\StarCluster.ScenarioRunner.csproj --configuration Release --no-build -- tl1-phase-a --output-dir $tl1PhaseAOut}
 Write-Host '[4/8] C#/Python parity...';Invoke-PythonChecked $python @('-B',$research,'--repo',$repositoryRoot,'parity','--output-dir',$parityOut) 'CP158 parity failed';$parity=Read-Json (Join-Path $parityOut 'summary.json');if(-not [bool]$parity.passed -or [int]$parity.cases -ne 25){throw 'CP158 parity mismatch.'}
 Write-Host '[5/8] CP158 focused PF2/AUX tests...';$sim=Join-Path $repositoryRoot 'tools\simulation';$oldPath=$env:PYTHONPATH;try{if([string]::IsNullOrWhiteSpace($oldPath)){$env:PYTHONPATH=$sim}else{$env:PYTHONPATH=$sim+[IO.Path]::PathSeparator+$oldPath};& $python.Command @($python.Args+@('-B','-m','unittest','discover','-v','-s','tools/simulation/tests','-p','test_cp158_*.py'));if($LASTEXITCODE -ne 0){throw 'CP158 focused tests failed.'}}finally{$env:PYTHONPATH=$oldPath}
 Write-Host '[6/8] CP158 PF2 conformance + 44.723375M AUX plan...';Invoke-AuxChecked @('plan','--out',$planOut) 'CP158 plan failed';$pl=Read-Json (Join-Path $planOut 'summary.json');if([int]$pl.candidateTlPoints -ne 703 -or [int]$pl.screenLegalCells -ne 497555 -or [int]$pl.plannedDeepCells -ne 277160 -or [int]$pl.pairwiseLegalCells -ne 169040 -or [int64]$pl.substantiveCombatTrials -ne 44723375){throw 'CP158 plan mismatch.'};Copy-Pf2Snapshot
 Write-Host '[7/8] CP158 live AUX architecture smoke (8 families)...';Invoke-AuxChecked @('smoke','--out',$smokeOut) 'CP158 smoke failed';$sm=Read-Json (Join-Path $smokeOut 'summary.json');if(-not[bool]$sm.passed -or [int]$sm.families -ne 8 -or [int]$sm.combatTrials -ne 8){throw 'CP158 architecture smoke mismatch.'}
 Write-Host '[8/8] Writing RepositoryOnly acceptance...';$bm=Read-Json (Join-Path $repositoryRoot 'docs\validation\evidence\checkpoint-158\research_execution_baseline_manifest_v0_2.json');$summary=[ordered]@{schemaVersion='star-cluster-cp158-repository-only-acceptance-v0.1';checkpoint=158;repositoryOnly=$true;failedGates=@();python=$pythonVersion.Trim();dotnetSdk=$dotnetVersion;buildPassed=$true;pythonTestsPassed=574;xunitTotal=$total;xunitPassed=$passed;xunitFailed=$failed;xunitSkipped=$skipped;scenarioRunnerSelfTestsPassed=70;deterministicScenarioCorpusPassed=$true;tl1PhaseACorpusPassed=$true;researchParityPassed=25;cp158FocusedTestsPassed=30;pendingFinalizationBaselineId='CP158-PF2';pendingFinalizationMatrixSha256=$bm.materializedMatrixSha256;pf2ClassificationSplitCompleted=$true;productionAuthorityChanged=$false;architectureSmokeCombats=8;candidateTlPoints=703;screenLegalCells=497555;deepLadders=64;plannedDeepCells=277160;pairwiseCells=169040;plannedSubstantiveCombatTrials=44723375;substantiveCombatTrials=0;tuningAllowed=$false;automaticPromotion=$false;nextPass='AUX evidence interpretation and pending-finalization candidate selection';finalMajorPass='Reactor/TP Scarcity and Whole-Ship Equilibrium'};$summary|ConvertTo-Json -Depth 8|Set-Content $repoOnlySummary -Encoding UTF8;Invoke-PythonChecked $python @('-B',$contract,'--repo',$repositoryRoot,'--native-results',$outRoot) 'CP158 RepositoryOnly contract failed';Write-Host 'CP158 RepositoryOnly PASSED. Run again without -RepositoryOnly to execute/resume 44,723,375 substantive combats.' -ForegroundColor Green
 }finally{Pop-Location};exit 0}
if(-not(Test-Path $repoOnlySummary)){throw 'Run CP158 -RepositoryOnly first in this same extraction.'};Push-Location $repositoryRoot;try{
 Write-Host '[final 1/8] Revalidating repository, PF2, and RepositoryOnly state...';Invoke-PythonChecked $python @('-B',$preflight,'--repo',$repositoryRoot) 'CP158 final preflight failed';Invoke-PythonChecked $python @('-B',$contract,'--repo',$repositoryRoot,'--native-results',$outRoot) 'CP158 RepositoryOnly state contract failed'
 Write-Host '[final 2/8] Executing/resuming matched PF2 no-AUX baseline (342,500)...';$baseSummary=Join-Path $baselineOut 'summary.json';if(Valid-Summary $baseSummary 'baseline' 342500){Write-Host '       CP158 baseline valid; reusing.'}else{if(Test-Path $baselineOut){Remove-Item -Recurse -Force $baselineOut};Invoke-AuxChecked @('baseline','--out',$baselineOut,'--jobs',[string]$Jobs) 'CP158 baseline failed'}
 Write-Host '[final 3/8] Executing/resuming 703-candidate broad AUX screen (12,438,875)...';New-Item -ItemType Directory -Force -Path $screenRoot|Out-Null;$planRows=Import-Csv -LiteralPath (Join-Path $planOut 'aux_candidate_counts.csv')|Where-Object{[int]$_.candidate_count -gt 0};$bi=0;foreach($r in $planRows){$bi++;$dir=Join-Path $screenRoot ("{0}-TL{1}" -f $r.family,$r.tl);$sum=Join-Path $dir 'summary.json';$expected=[int64]$r.legal_cells*25;if(Valid-Summary $sum 'screen-batch' $expected){Write-Host("       CP158 screen batch {0}/{1} {2} TL{3} valid; reusing." -f $bi,$planRows.Count,$r.family,$r.tl)}else{if(Test-Path $dir){Remove-Item -Recurse -Force $dir};Write-Host("       CP158 screen batch {0}/{1} {2} TL{3}: {4} combats" -f $bi,$planRows.Count,$r.family,$r.tl,$expected);Invoke-AuxChecked @('screen','--out',$dir,'--family',$r.family,'--tl',[string]$r.tl,'--jobs',[string]$Jobs) "CP158 screen $($r.family) TL$($r.tl) failed"}}
 if(Test-Path $screenMerged){Remove-Item -Recurse -Force $screenMerged};Invoke-AuxChecked @('merge-screen','--baseline',(Join-Path $baselineOut 'aux_baseline_context_results.csv'),'--batches',$screenRoot,'--out',$screenMerged) 'CP158 screen merge failed';$sms=Read-Json (Join-Path $screenMerged 'summary.json');if([int64]$sms.combatTrials -ne 12438875 -or [int]$sms.candidates -ne 703 -or [int]$sms.errorTrials -ne 0){throw 'CP158 screen merged scale mismatch.'}
 Write-Host '[final 4/8] Synthesizing 64 architecture-stratified whole-lifecycle AUX ladders...';New-Item -ItemType Directory -Force -Path $ladderOut|Out-Null;$laddersCsv=Join-Path $ladderOut 'aux_ladder_candidates.csv';Invoke-AuxChecked @('synthesize','--screen',(Join-Path $screenMerged 'aux_candidate_summary.csv'),'--out',$laddersCsv) 'CP158 ladder synthesis failed';$ladderIds=@(Import-Csv -LiteralPath $laddersCsv|Select-Object -ExpandProperty ladder_id -Unique);if($ladderIds.Count -ne 64){throw "CP158 expected 64 deep ladders, found $($ladderIds.Count)."}
 Write-Host '[final 5/8] Executing/resuming 64-ladder full-resource deep confirmation (27,716,000)...';New-Item -ItemType Directory -Force -Path $deepRoot|Out-Null;$batches=[Math]::Ceiling($ladderIds.Count/2.0);for($b=0;$b -lt $batches;$b++){$start=$b*2;$end=[Math]::Min($ladderIds.Count,$start+2);$dir=Join-Path $deepRoot ("batch-{0:D2}" -f ($b+1));$sum=Join-Path $dir 'summary.json';$reuse=$false;if(Test-Path $sum){try{$ds=Read-Json $sum;$expectedIds=@($ladderIds[$start..($end-1)]);$actualIds=@($ds.ladderIds);$reuse=[bool]$ds.passed -and [string]$ds.mode -eq 'deep-batch' -and [int]$ds.errors -eq 0 -and ($actualIds.Count -eq $expectedIds.Count) -and (-not(Compare-Object $actualIds $expectedIds))}catch{$reuse=$false}};if($reuse){Write-Host("       CP158 deep batch {0}/{1} ladders {2}-{3} valid; reusing." -f ($b+1),$batches,$start,($end-1))}else{if(Test-Path $dir){Remove-Item -Recurse -Force $dir};Write-Host("       CP158 deep batch {0}/{1} ladders {2}-{3}" -f ($b+1),$batches,$start,($end-1));Invoke-AuxChecked @('deep','--ladders',$laddersCsv,'--out',$dir,'--start',[string]$start,'--end',[string]$end,'--jobs',[string]$Jobs) "CP158 deep batch $($b+1) failed"}}
 if(Test-Path $deepMerged){Remove-Item -Recurse -Force $deepMerged};Invoke-AuxChecked @('merge-deep','--baseline',(Join-Path $baselineOut 'aux_baseline_context_results.csv'),'--batches',$deepRoot,'--out',$deepMerged) 'CP158 deep merge failed';$dms=Read-Json (Join-Path $deepMerged 'summary.json');if([int64]$dms.combatTrials -ne 27716000 -or [int]$dms.ladders -ne 64 -or [int]$dms.errorTrials -ne 0){throw 'CP158 deep merged scale mismatch.'}
 Write-Host '[final 6/8] Executing/resuming center-point AUX pairwise interaction surface (4,226,000)...';New-Item -ItemType Directory -Force -Path $pairRoot|Out-Null;for($tl=1;$tl -le 9;$tl++){$dir=Join-Path $pairRoot ("TL{0}" -f $tl);$sum=Join-Path $dir 'summary.json';$reuse=$false;if(Test-Path $sum){try{$ps=Read-Json $sum;$reuse=[bool]$ps.passed -and [string]$ps.mode -eq 'pairwise' -and [int]$ps.errors -eq 0 -and [int]$ps.tlFilter -eq $tl}catch{$reuse=$false}};if($reuse){Write-Host("       CP158 pairwise TL{0} valid; reusing." -f $tl)}else{if(Test-Path $dir){Remove-Item -Recurse -Force $dir};Write-Host("       CP158 pairwise TL{0}" -f $tl);Invoke-AuxChecked @('pairwise','--out',$dir,'--tl',[string]$tl,'--jobs',[string]$Jobs) "CP158 pairwise TL$tl failed"}}
 if(Test-Path $pairMerged){Remove-Item -Recurse -Force $pairMerged};Invoke-AuxChecked @('merge-pairwise-batches','--batches',$pairRoot,'--baseline',(Join-Path $baselineOut 'aux_baseline_context_results.csv'),'--screen',(Join-Path $screenMerged 'aux_candidate_summary.csv'),'--out',$pairMerged) 'CP158 pairwise merge failed';$pms=Read-Json (Join-Path $pairMerged 'summary.json');if([int64]$pms.combatTrials -ne 4226000 -or [int]$pms.errorTrials -ne 0){throw 'CP158 pairwise merged scale mismatch.'}
 Write-Host '[final 7/8] Writing final AUX/PF2 native acceptance...';$bs=Read-Json (Join-Path $baselineOut 'summary.json');$ss=Read-Json (Join-Path $screenMerged 'summary.json');$ds=Read-Json (Join-Path $deepMerged 'summary.json');$ps=Read-Json (Join-Path $pairMerged 'summary.json');$ro=Read-Json $repoOnlySummary;$caps=[int64]$bs.turnCapSentinels+[int64]$ss.turnCapSentinels+[int64]$ds.turnCapSentinels+[int64]$ps.turnCapSentinels;$errors=[int64]$bs.errors+[int64]$ss.errorTrials+[int64]$ds.errorTrials+[int64]$ps.errorTrials;$final=[ordered]@{};$ro.psobject.Properties|ForEach-Object{$final[$_.Name]=$_.Value};$final['schemaVersion']='star-cluster-cp158-native-acceptance-v0.1';$final['repositoryOnly']=$false;$final['repositoryOnlyAccepted']=$true;$final['baselineCombatTrials']=[int64]$bs.combatTrials;$final['screenCombatTrials']=[int64]$ss.combatTrials;$final['deepCombatTrials']=[int64]$ds.combatTrials;$final['pairwiseCombatTrials']=[int64]$ps.combatTrials;$final['substantiveCombatTrials']=[int64]$bs.combatTrials+[int64]$ss.combatTrials+[int64]$ds.combatTrials+[int64]$ps.combatTrials;$final['substantiveTurnCapSentinels']=$caps;$final['substantiveErrors']=$errors;$final['deepLadders']=[int]$ds.ladders;$final['pairwiseCells']=169040;$final['automaticPromotion']=$false;$final['productionAuthorityChanged']=$false;if([int64]$final['substantiveCombatTrials'] -ne 44723375 -or $errors -ne 0){throw 'CP158 final substantive contract mismatch.'};$final|ConvertTo-Json -Depth 8|Set-Content $finalSummary -Encoding UTF8;Invoke-PythonChecked $python @('-B',$contract,'--repo',$repositoryRoot,'--native-results',$outRoot) 'CP158 final contract failed'
 Write-Host '[final 8/8] Packaging native results...';$zip=New-ResultZip;Write-Host "CP158 native acceptance PASSED. Results: $zip" -ForegroundColor Green
}finally{Pop-Location}
